DFE-Digital/get-teacher-training-adviser-service

app/views/layouts/application.html.erb, app/views/pages/10.html.erb, app/views/pages/100.html.erb, app/views/pages/110.html.erb, app/views/pages/120.html.erb, app/views/pages/130.html.erb, app/views/pages/140.html.erb, app/views/pages/150.html.erb, app/views/pages/160.html.erb, app/views/pages/170.html.erb, app/views/pages/180.html.erb, app/views/pages/190.html.erb, app/views/pages/20.html.erb, app/views/pages/200.html.erb, app/views/pages/210.html.erb, app/views/pages/220.html.erb, app/views/pages/230.html.erb, app/views/pages/30.html.erb, app/views/pages/40.html.erb, app/views/pages/50.html.erb, app/views/pages/60.html.erb, app/views/pages/70.html.erb, app/views/pages/80.html.erb, app/views/pages/90.html.erb, app/webpacker/styles/application.scss, config/routes.rb, yarn.lock
This is the first iteration of the front end screens required for the TTA workflow.
The are referenced by numbers which match up with the workflow diagram here ...
https://miro.com/app/board/o9J_kyYKvG4=/
=> Registration screens front end

.github/PULL_REQUEST_TEMPLATE.md, README.md
GITPB-121
Keep the README upto date to easy onboarding of new contributers
1. Correct naming for app
2. Updated dependency references
3. Removed unneeeded database steps
=> Updated README

app/views/layouts/application.html.erb, app/webpacker/packs/google_analytics.js
Request from Steven Fawcett
Add google analytics tag
Check is working on production, initial attempt with webpacker
=> google analytics tag added

app/views/layouts/application.html.erb
=> change order of scripts

app/webpacker/packs/google_analytics.js
=> set gtag url

app/views/layouts/application.html.erb
=> removed false chars

app/views/layouts/application.html.erb, app/webpacker/packs/google_analytics.js
=> conditional gtag

.github/workflows/build.yml
GITPB-233
Pipeline changes
Build -> Package -> Deploy (Test) -> 
Deploy to test should have needed the build
=> corrected needs clause

.github/workflows/build.yml
=> Corrected directory location

terraform/paas/application.tf, terraform/paas/dev.env.tfvars, terraform/paas/test.env.tfvars
=> Corrected route error

terraform/paas/application.tf, terraform/paas/provider.tf, terraform/paas/variables.tf
=> Adding variables to TF

app/views/registrations/_form.html.erb
https://dfedigital.atlassian.net/browse/GITPB-122
Add error box to all forms
submit form with blank input, shows error box in addition to individual error messages
=> extra error box

app/models/qualified_to_teach.rb, app/models/subject_interested_teaching.rb, app/models/what_subject_degree.rb, app/views/pages/230.html.erb, app/views/registrations/_qualified_to_teach.html.erb, app/views/registrations/_subject_interested_teaching.html.erb, app/views/registrations/_what_subject_degree.html.erb, spec/models/degree/subject_interested_teaching_spec.rb, spec/models/degree/what_subject_degree_spec.rb, spec/models/equivalent/subject_interested_teaching_spec.rb, spec/models/subject_interested_teaching_spec.rb, spec/models/what_subject_degree_spec.rb
change the subject list to be the same throughout
=> update subject list

app/views/pages/180.html.erb, app/views/registrations/_qualification_required.html.erb
content change to get the right GCSE qualification screens
=> content change for get the right GCSE qualifications

app/views/pages/190.html.erb, app/views/pages/210.html.erb, app/views/pages/home.html.erb
change phrase to 'teaching adviser'
=> change phrase to 'teaching adviser'

README.md
update readme with redis intructions for local development
=> update readme with redis instructions

app/views/pages/home.html.erb
=> home page content change

.github/workflows/pull.ym, Dockerfile, terraform/paas/application.tf, terraform/paas/backend.tf, terraform/paas/backend.tf.future, terraform/paas/dev.bk.vars, terraform/paas/dev.env.tfvars, terraform/paas/services.tf, terraform/paas/test.bk.vars, terraform/paas/variables.tf
=> Add docker file checks

config/environments/rolling.rb
=> redis configurations

.github/workflows/build.yml, terraform/paas/services.tf
=> Added memory policy

.github/workflows/build.yml, .github/workflows/main.yml, terraform/paas/test.env.tfvars
=> Deploy via terraform

config/environments/preprod.rb
connect redis server in preprod environment
_GetIntoTeachingRegister_session cookie should be visible in storage
=> redis in preprod environment

app/controllers/registrations_controller.rb, app/views/check_answers/degree/_callback_date.html.erb, app/views/check_answers/equivalent/_callback_date.html.erb
adds callback date helper to check answers pages
=> Callback date

.github/workflows/build.yml, terraform/paas/application.tf
Environment Variables for Development were incorrectly set, and should be the rolling variables.
=> Removed SECRETS

.github/workflows/build.yml, Gemfile, Gemfile.lock, config/environments/preprod.rb, config/environments/rolling.rb
Fix deployment out to dev environments
=> Fixes for Redis integration

.github/workflows/main.yml
Fix terraform for test environment
=> Fixed variable name

app/views/pages/home.html.erb
=> change the inset text

terraform/paas/application.tf, terraform/paas/dev.env.tfvars, terraform/paas/domain.tf, terraform/paas/test.env.tfvars, terraform/paas/variables.tf
Removed blue_green strategy and also added in ability to pickup beta domains
=> Removed errornous variable, and added optional secondary route

terraform/paas/variables.tf
Change from standard deployment to blue_green deployment
=> Changed to blue-green

app/views/check_answers/_primary_maths_english_grade4.html.erb, app/views/check_answers/degree/_primary_maths_english_grade4.html.erb, app/views/check_answers/studying/_primary_maths_english_grade4.html.erb
=> change helper method for primary_maths

app/models/equivalent/uk_callback.rb, app/models/uk_callback.rb, spec/factories/equivalent/equivalent_uk_callback.rb, spec/factories/uk_callback.rb, spec/models/equivalent/uk_callback_spec.rb
=> updated uk_callback

.github/workflows/cve.yml
=> Adding CVE Scanner

.github/workflows/build.yml, README.md
Adding Accessibility Scan to Post-Master Deployment on Development
=> Added Accessibility

Gemfile, Gemfile.lock, app/views/registrations/studying/_uk_completion.html.erb, spec/helpers/session_helper_spec.rb, spec/vcr/SessionHelper/_show_callback_time/returns_the_session_callback_time_value_as_a_string.yml
=> update api client gem version

config/initializers/get_into_teaching_api_client.rb
=> update api client config

config/initializers/get_into_teaching_api_client.rb
=> update api config again

config/initializers/get_into_teaching_api_client.rb
=> try string auth

.zap/rules.tsv, config/initializers/get_into_teaching_api_client.rb
=> reverted api config

app/models/equivalent/stage_interested_teaching.rb, app/views/registrations/_uk_candidate.html.erb, app/views/registrations/equivalent/_overseas_completion.html.erb, app/views/registrations/equivalent/_uk_completion.html.erb, app/views/registrations/studying/_stage_of_degree.html.erb, spec/models/equivalent/stage_interested_teaching_spec.rb
only secondary stage needs to ask for subject interested teaching
Update equivalent flow primary or secondary next step
Ignore the store class, just for reference atm
=> update equivalent flow

app/views/check_answers/_subject_interested_teaching.html.erb
fix for weird typo in show subject helper
=> fix show subject helper

terraform/statuscake/backend.tf, terraform/statuscake/dev.bk.vars, terraform/statuscake/dev.env.tfvars, terraform/statuscake/provider.tf, terraform/statuscake/resources.tf, terraform/statuscake/test.bk.vars, terraform/statuscake/test.env.tfvars, terraform/statuscake/variables.tf
=> Statuscake added

app/views/check_answers/_subject_interested_teaching.html.erb, app/views/registrations/_subject_like_to_teach.html.erb
add guidance link and revert typo
=> added guidance link

.github/workflows/build.yml, sonar-project.properties
Move sonarcloud properties into a file to make more accessible to developers and also bring it in-line with APP, to hopefully make it more accurate
=> Changed sonarcloud configuration to be more developer accessible

app/views/registrations/degree/_overseas_completion.html.erb, app/views/registrations/degree/_uk_completion.html.erb, app/views/registrations/studying/_overseas_completion.html.erb, app/views/registrations/studying/_uk_completion.html.erb
=> update uk completion

.github/workflows/build.yml, .github/workflows/release.yml, tests/confidence/healthcheck.sh
Confidence Tests added, which are run after deployment and check the applications health check endpoint, then checks the SHA is what is expected
=> Added smoke tests

app/models/studying/retake_science.rb, app/models/studying/science_grade4.rb, spec/models/studying/retake_science_spec.rb, spec/models/studying/science_grade4_spec.rb
we need to update the studying pathway as we do not ask for teaching subject in the primary phase
Updated science_grade4 / retake_science files and tests
=> update studying path

terraform/statuscake/resources.tf, terraform/statuscake/test.env.tfvars
Added Tags to statuscake to make finding tests easier
Changed the contact group to a specific one ( this has to be configured manually, which has been done )
renamed the tests to be a little more understandable
=> Status cake

app/views/check_answers/_telephone.html.erb
https://dfedigital.atlassian.net/browse/GITPB-596
The link to Telephone on equivalent/overseas_completion page was displaying as "not visited"
updated telephone partial to provide correct equivalent link
=> update overseas telephone link

.github/workflows/build.yml, .github/workflows/cve.yml, .github/workflows/release.yml
remove the old calls to sentry.io and replace with a github action that calls on release
=> Removed old sentry.io action, replaced with release action

.github/workflows/build.yml, .github/workflows/release.yml
Forced Terraform to use version 12.29 as version 13 fails
=> Force Terraform to use version 12.29

.github/workflows/ur.yml, terraform/paas/ur.bk.vars, terraform/paas/ur.env.tfvars
Creating new UR Environment
The YAML file in github should run from workflow user triggering, and should call terraform with ur.xxxx 
The terraform has 2 new files:
1. backend to store state, it must be ur rather than test or dev
2. The names of the applications/services in the second file must be ur rather than test or dev
=> Adding UR environment

terraform/paas/ur.env.tfvars
=> Space was incorrectly changed

Gemfile, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/pages/session_expired.html.erb, config/routes.rb, spec/requests/invalid_authenticity_token_spec.rb, spec/requests/pages_spec.rb
https://dfedigital.atlassian.net/browse/GITPB-418
On session expiry we need a graceful failure for ActionController::InvalidAuthenticityToken
Redirect to session-expiry page with post requests with invalid csfr token
=> Session expire error

.env.userresearch, app/helpers/application_helper.rb, app/webpacker/controllers/hotjar_controller.js, spec/helpers/application_helper_spec.rb, spec/javascript/controllers/hotjar_controller_spec.js
GITPB-595
We need to log user research sessions to HotJar
1. Add HotJar controller
2. Add HotJar controller spec
Note: PR is currently based off another branch it derives from for clarity. Base will be changed to `master` prior to merging
**Should only be merged after GITPB-628 is merged**
Code is derived from GiT Website and has been tested extensively there
=> GITPB-595 Added HotJar logging

.github/workflows/ur.yml
GITPB-650
We need researchers to be able to access the service without a username and password
1. Drop passing env vars through from the pipeline
=> Removed username and password from UR pipeline

Gemfile, Gemfile.lock, spec/rails_helper.rb
This will be used to make the tests in the step models more concise.
=> Add shoulda-matchers gem

app/views/pages/home.html.erb
We want to be able to access the new journey locally and on the hosted development instance so that it's easy to access and test.
=> Point local and hosted dev environments to new journey

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/ur.yml
The cloud foundry team have decided to rename the files, this has caused our pipelines to fail. This change is to fix the pipelines only
=> Changed Location of CF Provider

app/helpers/application_helper.rb, app/webpacker/controllers/facebook_controller.js, app/webpacker/controllers/pinterest_controller.js, app/webpacker/controllers/snapchat_controller.js, spec/helpers/application_helper_spec.rb, spec/javascript/controllers/facebook_controller_spec.js, spec/javascript/controllers/pinterest_controller_spec.js, spec/javascript/controllers/snapchat_controller_spec.js
We should be logging analytics from the registration so that the service can be effectively promote.
1. Added Snapchat integration
2. Added Pinterest integration
3. Added Facebook integration
=> GITPB-683 Social media analytics

app/views/pages/home.html.erb
=> Add govuk-link class to anchor tags

public/robots.txt
GITPB-708
We don't want search engines indexing the site during private beta
1. Updated robots.txt to hide the site
=> Disable search engine indexing of the site

app/views/teacher_training_adviser/steps/_already_signed_up.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
new phone number is 0800 389 2501
https://trello.com/c/PVpwMJdn/303-phone-number-on-app-and-tta
=> update phone number

app/controllers/cookie_preferences_controller.rb, app/views/cookie_preferences/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_cookie_banner.html.erb, app/webpacker/controllers/analytics_base_controller.js, app/webpacker/controllers/cookie-acceptance_controller.js, app/webpacker/controllers/cookie_preferences_controller.js, app/webpacker/controllers/gtm_controller.js, app/webpacker/controllers/hotjar_controller.js, app/webpacker/javascript/cookie_preferences.js, app/webpacker/styles/application.scss, app/webpacker/styles/cookie-banner.scss, config/routes.rb, package.json, spec/javascript/controllers/analytics_spec_helper.js, spec/javascript/controllers/cookie-acceptance_controller_spec.js, spec/javascript/controllers/cookie_preferences_controller_spec.js, spec/javascript/controllers/facebook_controller_spec.js, spec/javascript/controllers/gtm_controller_spec.js, spec/javascript/controllers/hotjar_controller_spec.js, spec/javascript/controllers/pinterest_controller_spec.js, spec/javascript/controllers/snapchat_controller_spec.js, spec/javascript/cookie_preferences_spec.js, spec/requests/cookie_preferences_controller_spec.rb, yarn.lock
GITPB-713
We should now be asking the user to accept the cookie preferences on the TTA app
1. Add cookie preferences page
2. Add cookie acceptance banner
Note cookie policy is still being written - hence why thats linked to a non-existant page for now
=> GITPB-713 Add cookie prefs

.env.preprod, app/helpers/application_helper.rb, app/webpacker/controllers/twitter_controller.js, config/initializers/secure_headers.rb, spec/helpers/application_helper_spec.rb, spec/javascript/controllers/twitter_controller_spec.js
GITPB-667
We require the ability to integrate with twitters tracking pixels
1. Added support for twitters tracking pixels
=> GITPB-667 Added twitter tracking pixel support

.github/workflows/build.yml, Gemfile, Gemfile.lock, app/controllers/concerns/wizard_steps.rb, app/controllers/pages_controller.rb, app/controllers/teacher_training_adviser/steps_controller.rb, app/views/teacher_training_adviser/steps/_authenticate.html.erb, spec/requests/pages_spec.rb, spec/requests/sign_up_spec.rb
Add Brakeman to our CI pipeline to automatically scan for vulnerabilities
1. Added Brakeman gem
2. Run brakeman as part of CI run
3. Filter page template requests
4. Replaced a dynamic redirect
=> Add brakeman

.env.preprod, .env.production
Analytics are not currently enabled in production for most services and should be
Enable the analytics in both preprod and production environments
=> Enable analytics in preprod and production environment

config/initializers/secure_headers.rb
CSP is blocking facebook analytics
1. allow access for facebook analytics
=> Facebook CSP fix

.github/workflows/production.yml, terraform/paas/application.tf, terraform/paas/production.bk.vars, terraform/paas/production.env.tfvars, terraform/paas/services.tf, terraform/paas/test.env.tfvars, terraform/paas/ur.env.tfvars, terraform/paas/variables.tf
Prepare for production pipelines
=> Prepare for Production

terraform/paas/production.env.tfvars
Incorrectly names redis database
=> Corrected name of redis Service in production

app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_have_a_degree.html.erb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/_uk_callback.html.erb, spec/features/sign_up_spec.rb
- Change degree class copy
- Clarify callback reason with updated title
=> Minor copy updates

app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/_uk_callback.html.erb
Minor copy change to both callback booking steps.
=> Copy update to callback step

terraform/paas/production.env.tfvars, terraform/paas/test.env.tfvars, terraform/paas/ur.env.tfvars
=> Sfawcett123 patch 2

app/views/teacher_training_adviser/steps/_qualification_required.html.erb
update link on get the right gcse page
=> update link on get the right gcse page

app/views/pages/home.html.erb
Content have supplied new copy for this.
=> Update home page copy for returning teachers

config/initializers/secure_headers.rb
We should be allowing gtm pixels
1. Allow gtm pixels
=> Allow GTM images

config/environments/preprod.rb
The CRM team want to be able to test against the test CRM - going forward this needs to change to test anyway.
=> Point preprod to test API instance

app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_qualification_required.html.erb, app/views/teacher_training_adviser/steps/_uk_telephone.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
A number of copy updates signed off by Elizabeth.
=> Various copy updates/tweaks

app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_overseas_telephone.html.erb
=> Minor copy updates to home page and overseas telephone

app/views/pages/home.html.erb
=> Updated copy for the home page

app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_returning_teacher.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
=> change freephone time

terraform/statuscake/test.env.tfvars
=> Statuscake Updated

config/initializers/secure_headers.rb
N/a
Added doubleclick frames to Content Security Policy
1. Allow doubleclick to create frames
=> Added doubleclick frame support for CSP

config/initializers/secure_headers.rb
N/a
We are seeing CSP errors from googles add service pixel being blocked
Added an exception for Googles Ad Service
=> Added google adservice to CSP

config/initializers/secure_headers.rb
CSP fix for double click stats
=> CSP Fix for doubleclick stats

terraform/paas/application.tf
Reverts DFE-Digital/get-teacher-training-adviser-service#106
=> Revert "Update application.tf"

.github/dependabot.yml
N/a
We should keep track of dependencies which need updating
1. Expand dependabot checks to cover Ruby, NPM and Docker
=> Expanded dependabot checks to Ruby, NPM and Docker

Dockerfile
Dependabot Upgrade of docker image needs more thought
=> Reverse Dependabot Merge

.github/workflows/cve.yml
CVE scanner set to manual to reduce noise
=> Set to manual

Dockerfile
Alpine 12 has been out for a while and we should upgrade to it.
1. Modified dockerfile base image
=> Upgrade to Alpine 12

.env.preprod, .env.production, .env.rolling, .env.userresearch, Gemfile, Gemfile.lock, app/controllers/csp_reports_controller.rb, config/initializers/rack_attack.rb, config/initializers/secure_headers.rb, config/routes.rb, spec/requests/csp_reports_spec.rb, spec/requests/rate_limiting_spec.rb
[Trello-429](https://trello.com/c/j2g8AgvM/429-send-csp-violations-to-kibana-instead-of-sentry)
Lift and shift of https://github.com/DFE-Digital/get-into-teaching-app/pull/487
=> Send CSP violations to Logit.io

.github/workflows/build.yml
https://trello.com/c/3XjSChte
We have javascript tests and they should be getting run as part of the CI tests
1. Add additional step to install the required dependencies and run the specs
=> Added Javascript tests to CI

.github/workflows/build.yml
Variable seems to have got through, I think it maybe because it was not able to merge the change
=> Javascript calls wrong Docker

app/views/layouts/_footer.html.erb
=> Fix the cookie footer link

.github/workflows/build.yml, .github/workflows/production.yml, .github/workflows/release.yml, .github/workflows/ur.yml, terraform/paas/provider.tf, terraform/paas/versions.tf
=> Terraform 13.4

.github/workflows/statuscake.yml, terraform/statuscake/provider.tf
=> Upgraded Terraform for Status Cake

.github/workflows/build.yml, .github/workflows/production.yml, .github/workflows/release.yml, terraform/paas/application.tf, terraform/paas/backend.tf, terraform/paas/dev.env.tfvars, terraform/paas/domain.tf, terraform/paas/production.env.tfvars, terraform/paas/routes.tf, terraform/paas/services.tf, terraform/paas/space.tf, terraform/paas/test.env.tfvars, terraform/paas/ur.env.tfvars, terraform/paas/variables.tf
Github are rate limiting anonymous pulls, this may effect the UK Gov Paas, so by adding credentials that stops.
Also ran **terraform fmt**
=> Add Credentials to Docker Deploy

.github/workflows/new_build.yml, .github/workflows/new_deploy.yml
Split Build and Deploy into two distinct jobs
**Build**
- Create a docker image
- Carries out test
- Triggers Deploy
**Deploy**
- Deploy to the PaaS
=> New Build Method

.github/workflows/build.yml, .github/workflows/cve.yml, .github/workflows/deploy.yml
=> Run CVE on review builds

.github/workflows/deploy.yml
=> Ensured Release is locked to commit sha

.github/workflows/build.yml, .github/workflows/deploy.yml
[CD](https://trello.com/c/UQrm3g59/516-platform-continuous-deployment)
The release name needs to tie in with the PR
=> Release Tag given better name

.github/workflows/deploy.yml
Bug fix on pipeline only
Used the wrong variable so did not work when running inside github
=> Used wrong variable

.github/workflows/cypress.yml
A new workflow has been added to the pipelines. This will allow the manual running of the Front End tests, selecting the TTA tests only. This also enables the CI-CD pipeline for delivery to production to automatically execute this workflow, and then when completed without error it can the automatically push the changes forward.
Initial development requires this workflow to be pushed to the master branch ( with only manual execution ) so that testing and further changes can be made.
=> Initial Trigger of File

.github/workflows/build.yml, .github/workflows/deploy.yml
If two or more PRs are merged at same time, then it can cause
problems on deploy
=> Correcting Race Condition

.github/workflows/build.yml
Bug fix where sha reference didnt have {{ }}
=> Reference problem

.github/workflows/build.yml
reference should be github.ref. all this sha stuff was nonsense
=> Ref corrected

.github/workflows/build.yml
The PR reference still isnt getting to the production stage. Trying to push through each stage
=> Passing through reference

.github/workflows/build.yml
Trying to solve the tag problem
=> renamed new_tag to tag

.github/workflows/build.yml
=> Trying to resolve tag issue

.github/workflows/build.yml
=> Another attempt at fixing tag issue

.github/workflows/build.yml
Production had a space in the passed parameter
=> Spurious Space in production trigger

.github/labeler.yml
Added extra checks to help identify a Ruby change
=> Additional Values to identify a ruby change

.github/workflows/build.yml, .github/workflows/cve.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/owasp.yml
Used common names for environment variables, and consistently used them
to replace hard coded names, thus allowing for easier code reuse.
=> Common Environment Variable Names

app/views/pages/cookies.html.erb
This is for the LID tracking pixel.
=> Add DAX cookie policy details

.github/workflows/build.yml
Call Cypress Tests from TTA Build workflow
=> Call Cypress Tests from Repository

.github/workflows/build.yml
There is a need to set the environment variables at each job when using common environment variables
=> Setup Environment needed with each job

.github/workflows/build.yml
[Race Conditions](https://trello.com/c/zFSnSfND/733-race-condition-in-pipelines)
When two builds are run at the same time, a race condition can occur
Add turnstyle to try and limit impact of race conditions
None really
=> add turnstyle to main workflow

terraform/paas/test.env.tfvars
Add the staging route for adviser
=> Add Staging Route

.github/workflows/deploy.yml
See if removing single quotes in Job Name help with problem where it isn't finding waiting job
=> Remove Single Quotes

.dockerignore, Dockerfile
Upgrade to Alpine 3.13 now 3.13.1 is out
1. Change base image
2. Exclude all varients of local env files
=> Upgraded to Alpine 3.13

.github/workflows/build.yml, .github/workflows/cve.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/manual.yml, .github/workflows/owasp.yml, .github/workflows/trello.yml, terraform/paas/application.tf, terraform/paas/data.tf, terraform/paas/dev.env.tfvars, terraform/paas/production.env.tfvars, terraform/paas/provider.tf, terraform/paas/review.env.tfvars, terraform/paas/statuscake.tf, terraform/paas/test.env.tfvars, terraform/paas/variables.tf
[Review storage of secrets](https://trello.com/c/flZVRexA/384-platform-review-storage-of-secrets)
Secrets moved from github to Azure Key Vault
This does not effect the product, only the workflows.
=> Devops/azure secrets/initial

app/helpers/application_helper.rb, app/views/cookie_preferences/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_cookie_banner.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb, app/webpacker/controllers/analytics_base_controller.js, app/webpacker/controllers/cookie_preferences_controller.js, app/webpacker/controllers/lid_controller.js, app/webpacker/styles/application.scss, package.json, spec/helpers/application_helper_spec.rb, spec/javascript/controllers/cookie-acceptance_controller_spec.js, spec/javascript/controllers/cookie_preferences_controller_spec.js, spec/javascript/controllers/facebook_controller_spec.js, spec/javascript/controllers/gtm_controller_spec.js, spec/javascript/controllers/lid_controller_spec.js, spec/javascript/controllers/pinterest_controller_spec.js, spec/javascript/controllers/snapchat_controller_spec.js, spec/javascript/controllers/twitter_controller_spec.js, spec/support/matchers/analytics_matcher.rb, yarn.lock
https://trello.com/c/teYsKRe4
We should use the current version of Stimulus
1. Upgraded dependency to Stimulus 2
2. Updated controllers to take advantage of new 'target' and Value api's in Stimulus
=> Stimulus 2 upgrade

.env.preprod, .env.rolling, config/environments/preprod.rb, config/environments/rolling.rb, config/initializers/rack_attack.rb
Reverts DFE-Digital/get-teacher-training-adviser-service#482
=> Revert "Add Fail2ban to Rack::Attack config"

.env.preprod, .env.rolling, config/environments/preprod.rb, config/environments/rolling.rb, config/initializers/rack_attack.rb
Reverts DFE-Digital/get-teacher-training-adviser-service#533
=> Revert "Revert "Add Fail2ban to Rack::Attack config""

config/initializers/rack_attack.rb
We should be banning hostile actors, _but_ also not banning our own CDN if the site is accessed via the CDN
1. Log some debug data in a ban to figure out whats going on. I think I know but want to check before trying to solve it.
Not suitable for production but not enabled in production yet anyway
=> Added debug data to ban message

.github/workflows/deploy.yml
Validate the azure keys before usage, to prevent badly formed keys from causing issues further down the pipeline.
This process does not effect the TTA, it is a step that prevents deployment if the key was invalid. The deployment probably would have failed anyway due to the invalid key, but under certain circumstances the error with the key details could get logged.
https://github.com/DFE-Digital/get-teacher-training-adviser-service/actions/runs/617232479
=> Validate Azure Keys

app/views/pages/home.html.erb
N/A
This suggestion was made by the returners team. The PR was raised so we
have a place to discuss the wording rather than to suggest this should
be committed immediately as-is.
=> Add QTS to the list of reqs on the homepage

.github/workflows/trello.yml
We use the code three times in different repositories, and we also might want to use the code in other projects. so we have decided to move it to a common repository
Github action [AddTrelloComment](https://github.com/DFE-Digital/github-actions/tree/master/AddTrelloComment) created
Does not effect application
Should not impact workflows
=> Using Common Trello Action

app/views/shared/_cookie_banner.html.erb
=> Draft Public Beta cookie banner

.github/workflows/deploy.yml, .github/workflows/manual.yml, terraform/paas/.gitignore, terraform/paas/provider.tf, terraform/paas/ur.bk.vars, terraform/paas/ur.env.tfvars
https://trello.com/c/vrk3CHph/1479-create-ur-environment
The User Researcher requires a stable environment to carry out there work
New UR Application installed into Test
No changes to application
=> UR Environment Created

.github/workflows/build.yml, .github/workflows/manual.yml, terraform/paas/production.env.tfvars
Network policies are required for monitoring to work correctly, but they seem to go invalid when a deployment of the application is made we have produced a task that fixes them, but this needs to be run whenever a deployment is carried out.
This is a pipeline change only
=> Run network fix

.github/workflows/build.yml, Dockerfile, Gemfile, Gemfile.lock, README.md, app/models/application_record.rb, config/application.rb, config/database.yml, config/environments/development.rb, config/environments/production.rb, config/initializers/new_framework_defaults_5_2.rb, config/initializers/new_framework_defaults_6_0.rb, db/schema.rb
[Trello-1514](https://trello.com/c/fnHpXkZt/1514-add-postgres-to-tta-service)
We require a storage mechanism for the TTA feedback form submissions and our current options aren't a good fit for this feature (GA, Prometheus, Logs).
- Enable ActiveRecord
Enable ActiveRecord in Rails and configure production database to point to the `postgres` instance in `VCAP_SERVICES`.
Uses a postgres service in the GitHub Action for running tests.
Nothing has changed as far as the user is concerned in this PR; as long as the app passes CI and boots in the review space it should be good.
=> Enable ActiveRecord

.github/workflows/deploy.yml
Remove PLAN step
The PLAN step can in certain conditions expose secrets, so although we do not think it will happen, we want to be safe rather than sorry
=> Remove Plan

app/controllers/teacher_training_adviser/feedbacks_controller.rb, spec/requests/feedback_spec.rb
The basic auth was being applied to all actions in a production instead of just the `index` and `export` actions. This went un-noticed in the rolling/preprod environments due to the site-wide authentication being expected on all pages anyway.
Only apply basic auth to `index` and `create` actions, _unless_ on a production-like (but not production) environment.
Don't apply basic auth when in dev/test.
I may have another stab at making this clearer, but this should resolve the issue in production for now so we can re-roll the feature back out.
=> Fix basic auth prompt in production

.env.production
[Trello-1564](https://trello.com/c/JHvvyYie/1564-disable-tracking-pixels)
We want to disable the following tracking pixels in production as we are instead implementing them via GTM:
```
Pinterest
Snapchat
Google AdWords
Twitter
Facebook
```
- Disable tracking pixels in production
=> Disable tracking pixels in production

Gemfile, Gemfile.lock
This PR will upgrade Puma to latest version to benefit from performance improvements and bug fixes.
Will also silence #678
=> Upgrade Puma to v5.3.1

app/views/teacher_training_adviser/steps/_subject_not_found.html.erb
=> more about 'you' - less about 'us' and 'them'

app/views/teacher_training_adviser/steps/_no_degree.html.erb
* give the link to GIT in the context of qualified teacher status so it's more contextual 
* send user to a simpler/more direct search on UCAS 
* use lowercase QTS in line with rest of site 
* make link text more accessible
=> lower case QTS and better links

config/locales/en.yml
Add hint text in order to address visa eligibility issues.
=> Add hint text to country selection step

app/views/teacher_training_adviser/steps/_authenticate.html.erb, app/views/wizard/steps/_authenticate.html.erb, spec/features/sign_up_spec.rb
=> 2 lines say the same thing - combine

app/views/teacher_training_adviser/steps/_accept_privacy_policy.html.erb
@ethax-ross - I'm guessing I've done something funky here!? was unable to review as I made the change
=> put link to privacy policy in the text rather than separate

app/views/teacher_training_adviser/steps/_no_degree.html.erb
Tiny fix to update the capitalisation of `BSc`
- Update capitalisation of `BSc`
=> Fix capitalisation of `BSc`

config/locales/en.yml
=> Correct mistake in feedback questionnaire

app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb, config/locales/en.yml
N/A
https://docs.google.com/document/d/1zos7X-rsD8MH08GSw0eXQ4n9z11VLppS_fu9jPBvb_I/edit
=> Update the copy on the sign up complete page

config/locales/en.yml
Updating QTS link for overseas qualified teachers
=> Update QTS URL

config/locales/en.yml
Just notices this line needs to change for year end too.
=> Minor change to remove reference to September 2021

.github/workflows/build.yml
Anchore has far too many false positives so replacing with Snyk
=> Replace Anchore with Snyk

config/initializers/secure_headers.rb
These have shown up with the new GTM container, so I've added them to the corresponding directives.
=> Minor CSP tweaks

.github/workflows/destroy.yml
Delete terraform State file after review is destroyed
=> Delete state file

app/views/pages/home.html.erb
https://trello.com/c/J6YOhH0r/2680-change-call-centre-opening-hours-for-christmas
Add a banner to the homepage letting people know there might be delays over the Christmas period.
Co-authored with @EllieNodder
=> Added a banner to homepage about Christmas

app/views/pages/home.html.erb
https://trello.com/c/oNwFqjlN/2700-remove-amended-christmas-contact-hours
=> Removing Christmas contact hours notification banner

Dockerfile
See https://security.snyk.io/vuln/SNYK-ALPINE315-GMP-2386788
=> Security patch gmp in docker image

app/models/teacher_training_adviser/steps/subject_like_to_teach.rb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_subject_not_found.html.erb, spec/models/teacher_training_adviser/steps/subject_like_to_teach_spec.rb
https://trello.com/c/aVg2qWZs/2730-returners-update-content-to-cover-widening-of-eligibility-for-rtta-support?filter=member:ellienodder
=> Adding new RTTA subjects to get an adviser start page

.github/workflows/build.yml
It makes sense to build review apps for draft PRs.
- Allow review app deployment for draft PRs
- Trim any trailing whitespace
=> Allow review apps to be built on draft PRs

app/views/pages/home.html.erb
The site at the old link appears to have broken; it's just a Plesk admin login and a certificate error.
=> Update the link for teachers in Wales

.github/workflows/actions/deploy/action.yml, .github/workflows/actions/owasp/action.yml, .github/workflows/build.yml, .github/workflows/destroy.yml, .github/workflows/manual.yml, Gemfile.lock
=> Various dependency updates

Makefile
https://trello.com/c/AmqiZOuv
Remove secrets from rails encrypted secrets, centralise in Azure keyvault, provide a safe and convenient place to store secrets used for local development
Makefile target to edit local secrets
Try `make local print-app-secrets` and `make local edit-app-secrets`
=> [559] Local development keyvault

.github/workflows/actions/deploy/action.yml, .github/workflows/actions/owasp/action.yml, .github/workflows/build-nocache.yml, .github/workflows/build.yml, .github/workflows/manual.yml, .github/workflows/trello.yml, Dockerfile
Docker build layers are cached to optimise build performance but sometimes the base image is updated so we need to rebuild it.
Rebuild once a week on Sunday or run manually as required.
Run the new workflow
=> [546] Rebuild docker cache workflow

app/views/teacher_training_adviser/feedbacks/thank_you.erb, app/views/teacher_training_adviser/steps/_no_degree.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
https://trello.com/c/XCo7NCJi/3126-check-internal-links-for-new-nav
=> Changing ways to train link on no degree page

Dockerfile
See https://security.snyk.io/vuln/SNYK-ALPINE316-PCRE2-2869397
=> Patch pcre2 vulnerability

app/views/teacher_training_adviser/steps/_subject_not_found.html.erb, config/locales/en.yml
https://trello.com/c/1MqGp3ws/3368-update-backlinks-on-tta-funnel
Updating the URLs in the TTA funnel, getting rid of any links to deleted pages and adding in the new ones.
=> updating URLs for international

.tool-versions, Makefile, terraform/paas/dev.bk.vars, terraform/paas/production.bk.vars, terraform/paas/provider.tf, terraform/paas/review.bk.vars, terraform/paas/test.bk.vars, terraform/paas/ur.bk.vars, terraform/paas/variables.tf
https://trello.com/c/FvvgC3LY
Review apps not deleted
Make it easier to troubleshoot deployed apps locally
Similar to GiT
=> [648] Run terraform locally

app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_returning_teacher.html.erb, config/locales/en.yml
https://trello.com/c/HjAovzqh/3512-update-tta-funnel-start-page-to-address-ineligible-users-signing-up-to-rttas
The international team have flagged an issue that RTTAs are having - that they get a lot of international people signing up for an RTTA who do not have QTS and therefore are not eligible for an RTTA. We should tweak the copy to make it clearer for international users.
=> Updating for ineligible international users

app/views/pages/home.html.erb
https://trello.com/c/imulU4A0/3576-consider-how-to-signpost-people-who-are-ineligible-for-an-adviser-to-the-git-website
=> adding link back to GIT for those ineligible for an adviser

app/views/pages/home.html.erb
Kat pointed out that the current wording could be confusing to returners, so I'm editing the copy so it applies to all users.
=> Updating link back to GIT

app/views/pages/home.html.erb, spec/features/sign_up_spec.rb
https://trello.com/c/cM2bchoj/3478-update-the-tta-content-to-cover-the-revamped-eea-service
=> Updating adviser funnel start page

.github/workflows/actions/deploy/action.yml, .github/workflows/actions/owasp/action.yml, .github/workflows/build.yml, .github/workflows/destroy.yml
https://trello.com/c/BYSSVCNY
Reduce dependabot PRs
=> [701] Pin Github actions to the major version only

Dockerfile
https://trello.com/c/To8PNXVI
Over time as security vulnerabilities are fixed, the number of patched packages can increase. Fixed packages are regularly published to the relevant package stores and in this instance several fixed package versions are now available on the Alpine Linux package store.
Remove unrequired package installations from the `Dockerfile`
=> Remove packages now available on Alpine Linux packages site

app/views/teacher_training_adviser/steps/_already_signed_up.html.erb, app/views/teacher_training_adviser/steps/_no_degree.html.erb, app/views/teacher_training_adviser/steps/_primary_returner.erb, app/views/teacher_training_adviser/steps/_qualification_required.html.erb, spec/features/sign_up_spec.rb
https://trello.com/c/RWh0xun9/4100-review-the-error-handling-pages-on-adviser-funnel
We want to tweak the dead end pages in the adviser funnel for a better user experience and to better support users signing up for the service
=> Editing dead end adviser funnel screens

app/views/errors/forbidden.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/too_many_requests.html.erb, app/views/errors/unprocessable_entity.html.erb, spec/requests/pages_spec.rb
https://trello.com/c/TU5jzJOx/4265-improve-adviser-service-404-page
Updating the 404 page content.
=> Updating 404 page text

app/views/pages/accessibility.html.erb
https://trello.com/c/P0njxMzH
We want to update our accessibility statement to say that we have booked our next external audit.
=> Update accessibility statement with holding text

Dockerfile
[Trello-4466](https://trello.com/c/oEUvZ4LN/4466-fix-snyk-vulnerabilities)
https://security.snyk.io/vuln/SNYK-ALPINE316-TIFF-3370742 
https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3368756
=> Patch vulnerabilities in Docker image

app/views/pages/accessibility.html.erb
https://trello.com/c/QFAorFt7
We need to update our accessibility statement on the adviser site due to a change in our external audit arrangements.
=> Update accessibility statement to amend audit arrangements

Dockerfile
See [https://security.snyk.io/vuln/SNYK-ALPINE316-NCURSES-5606597](https://security.snyk.io/vuln/SNYK-ALPINE316-NCURSES-5606597)
=> Put correct version of ncurses-libs
