.github/workflows/build.yml, .github/workflows/release.yml
Credentials on pipeline moved from global to each step and there is an outside possibility someone could hijack them if global
=> Adding credentials for all steps

.github/workflows/build.yml
Trying to resolve a problem where the code coverage report outputs the data as /app/app/models/*** where as the sonarcloud ingestion is expecting /app/models/****
=> Output of coverage is full directory, we cannout use that

.github/workflows/build.yml
Only Run the Accessibility Tests on a Master Push
To scan we need the website running and that only happens after a push to master
=> only build run accessibility tests on  master

terraform/paas/versions.tf
Github must be rolling out 0.12.29 as I have found it had upgraded one of the state files, but it mainly uses 0.12.28 and that causes problems if it is upgraded.  
Been more specific with the version to prevent this
=> Specify Version 0.12.28

config/routes.rb
We should show clear and appropriately styled error pages when the user encounters a 500 or 404 scenario. Currently instead they are seeing a plain white fallback screen when visiting an unknown page (eg https://get-teacher-training-adviser-service-dev.london.cloudapps.digital/missing)
1. Move the 'catch all' route for the pages controller below other routes to give others, including the error screens, higher priority.
1. Boot to production locally, and visit http://localhost:3000/missing - you should see a GovUK error page
=> Fix showing the GovUK error pages when hitting exceptions and/or missing pages

config/environments/preprod.rb, config/environments/production.rb, config/environments/rolling.rb, config/initializers/01_vcap_services.rb, config/initializers/redis.rb
The current preprod and rolling environments assume the presence of the VCAP_SERVICES env var - and the production environment does not use the VCAP_SERVICES env var to configure redis.
This prevents testing preprod and rolling environments locally and will also require further configuration of the production environment when it is deployed onto PaaS.
1. Always parse VCAP_SERVICES configuration into the `Rails.application.config` hash if it is set
2. If `REDIS_URL` is not set, and a redis config is present in the VCAP_SERVICES, use that to configure Redis
3. Check for Redis connectivity at boot and fail if not present.
This is set to deploy straight through to the rolling environment at present, as if it was on `master`. If that environment is still working than these changes are …
=> Update vcap configuration

app/services/api_client.rb, spec/helpers/session_helper_spec.rb, spec/models/date_of_birth_spec.rb, spec/models/studying/primary_retake_english_maths_spec.rb, spec/models/studying/retake_english_maths_spec.rb, spec/models/what_degree_class_spec.rb, spec/requests/basic_auth_spec.rb, spec/requests/registrations_spec.rb, spec/services/api_client_spec.rb
[GITPB-615](https://dfedigital.atlassian.net/browse/GITPB-615)
Looking at Sonarcloud there are a few gaps in the test coverage that we could plug.
- Fix tests using an incorrect model
- Ensure future dated date_of_birth is invalid
- Add test coverage to SessionHelper
- Fix ApiClient tests
- Add test coverage to WhatDegreeClass step
- Add test coverage for basic auth
- Add test coverage for RegistrationsController
=> Improve test coverage

config/environments/production.rb
We wish to share a single Redis instance between both apps, this means we need a way to isolate the keys
1. Namespace all keys under the `TTA` namespace
=> Namespace all cache keys in Redis

app/controllers/sitemaps_controller.rb, app/views/sitemaps/index.xml.erb
It doesn't make sense to expose the sign up steps to be indexed by search engines as they can't be accessed directly; only by progressing through the sign up flow.
Remove sign up steps from sitemap
=> Remove sign up steps from sitemap

.github/workflows/build.yml, spec/spec_helper.rb
The default RSpec logger is more concise when running specs locally. We still need the documentation and SonarQube loggers when running in CI though
1. Drop the hard coded use of the documentation logger
2. Dynamically enable the use of the documentation and sonarqube loggers in CI
=> Changed default RSpec logger back to default

app/helpers/session_helper.rb, app/views/check_answers/_uk_candidate.html.erb, spec/helpers/session_helper_spec.rb
Prevents an exploit where JS can be inputted into the address fields then evaluated on the review answers page.
Currently uses the `safe_format` method from privacy policy helper, but this will be refactored later on - the fix needs to go in now for the pen testers to verify.
Introduces a minor UI glitch (extra space from wrapping `<p>` tags)
=> Remove use of html_safe on show_uk_address

app/models/have_a_degree.rb
Previously we set `degree_status_id` and `degree_type_id` in a before_validation hook. This was changed to the degree_options setter, but now results in all three validation error messages displaying if the user leaves the form field blank.
We can either revert to the before_validation hook, which would cover all the validation scenarios, or remove validation from the `degree_status_id` and `degree_type_id`
Opted to place validations within a with_options conditional block
=> comment out validations

config/environments/development.rb, config/environments/production.rb, config/initializers/session_store.rb
In the test environment if the session store is overridden it causes the Capybara tests to misbehave; essentially clearing the session between each request (resulting in the sign up flows not working as the order depends on session data from previous steps).
Moves the session store config into development/production environments only.
=> Prevent overriding session store key in test environment

app/controllers/concerns/wizard_steps.rb, app/models/wizard/base.rb, app/models/wizard/step.rb, app/models/wizard/store.rb, spec/models/wizard/base_spec.rb, spec/models/wizard/step_spec.rb, spec/models/wizard/store_spec.rb, spec/support/shared_examples/wizard_support.rb
We are going to transition the TTA sign up to use the same format/classes as the GiT app mailing list/event wizards. This commit adds the base/core classes for the Wizard, Store and Step models.
We should look to move these classes into a gem going forward so that we can reuse them between both apps.
=> Add core wizard classes from GiT app

app/controllers/pages_controller.rb, app/validators/policy_validator.rb, app/validators/types_validator.rb, spec/validators/policy_validator_spec.rb, spec/validators/types_validator_spec.rb
The ApiClient will be removed along with the existing journey (once the new wizard is in place); instead we will call the GetIntoTeachingApiClient directly (adding the ApiClient is a needless abstraction; originally we thought it may do more, such as caching but that will be done in the gem itself going forward).
It is being decoupled in this commit from any classes/modules that will remain in the app once the old registrations flow is removed.
=> Decouple classes from the ApiClient

app/webpacker/scripts/back_link.js
If a back link is not on the page we get an error trying to modify the style of an undefined element.
=> Fix JS error when no back link is present

app/controllers/concerns/wizard_steps.rb, app/models/teacher_training_adviser/steps/authenticate.rb, app/models/teacher_training_adviser/steps/identity.rb, app/models/teacher_training_adviser/wizard.rb, app/models/wizard/issue_verification_code.rb, app/models/wizard/step.rb, app/models/wizard/steps/authenticate.rb, app/views/teacher_training_adviser/steps/_authenticate.html.erb, app/views/wizard/steps/_authenticate.html.erb, config/routes.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/authenticate_spec.rb, spec/models/teacher_training_adviser/steps/identity_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb, spec/models/wizard/step_spec.rb, spec/models/wizard/steps/authenticate_spec.rb, spec/requests/sign_up_spec.rb, spec/support/shared_examples/wizard_support.rb
[GITPB-415](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-415)
When a candidate enters their first/last/email we want to check if we have a matching candidate in the system already. If we do, a verification code should be emailed to the candidate that they can then use to 'authenticate' and we can pre-fill the sign up form.
- Send verification code on matchback
If a candidate enters a first/last/email that matches an existing candidate in the CRM we want to email them a verification code that can be used in a subsequent step to retrieve their details and pre-fill the form.
- Add authenticate step
Add the authenticate step that is shown if a match-back is successful. Allows the user to resend the verification code in case they didn't receive …
=> Issue verification code

app/models/teacher_training_adviser/wizard.rb, app/models/wizard/api_client_support.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb, spec/models/wizard/api_client_support_spec.rb, spec/requests/sign_up_spec.rb
[GITPB-592](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?issueParent=19117&selectedIssue=GITPB-592)
When the candidate has finished filling in the sign up form they hit 'complete', at which point a request should send all the gathered information to the API, which then puts it on a queue to go to the CRM.
- Submit payload to API at end of sign up
When the user completes the sign up we bundle the information they entered into a request that sends it to the API, where it gets queued before going on to the CRM.
Mostly a lift/shift from the GiT website - follows the same pattern.
=> Submit the Candidate information to the API

app/models/teacher_training_adviser/steps/qualification_required.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/qualification_required_spec.rb
Fixes a typo in the GCSE maths/english attribute name and adds test coverage for the secondary path when the candidate has no GCSE's.
=> Fix typo in GCSE maths/english attribute

README.md, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, spec/features/view_pages_spec.rb
We need to change title references to teacher training adviser to "get an adviser"
Change page title, header bar and header text on home page to "get an adviser"
=> change title to get an adviser

app/models/concerns/api_options.rb, app/models/teacher_training_adviser/steps/have_a_degree.rb, app/models/teacher_training_adviser/steps/stage_of_degree.rb, app/models/teacher_training_adviser/steps/what_degree_class.rb, app/views/teacher_training_adviser/steps/_have_a_degree.html.erb, config/locales/en.yml, spec/models/teacher_training_adviser/steps/have_a_degree_spec.rb, spec/support/shared_examples/wizard_support.rb
A couple of the review answer values either weren't populating due to a type mismatch when keying a hash and another was showing an incorrect value for the `HaveADegree` answer (it was using the value we store, capitalized instead of what we display to the user).
=> Fix review answer display issues

app/models/teacher_training_adviser/steps/identity.rb, app/models/teacher_training_adviser/steps/overseas_telephone.rb, app/models/teacher_training_adviser/steps/start_teacher_training.rb, app/models/teacher_training_adviser/steps/uk_address.rb, app/models/teacher_training_adviser/steps/uk_callback.rb, app/models/teacher_training_adviser/steps/uk_telephone.rb, spec/models/teacher_training_adviser/steps/identity_spec.rb, spec/models/teacher_training_adviser/steps/overseas_telephone_spec.rb, spec/models/teacher_training_adviser/steps/uk_address_spec.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb, spec/models/teacher_training_adviser/steps/uk_telephone_spec.rb, spec/support/shared_examples/sanitize_input.rb
- Sanitize text input fields
On user inputted-text we want to ensure that white space is stripped from the leading/trailing edges and if the user enters an empty string we save it as `nil`.
- Find correct year from year_range
=> Sanitise user-inputted text values

app/models/teacher_training_adviser/steps/qualification_required.rb, spec/features/sign_up_spec.rb
Previously we were not showing the `QualificationRequired` step if the user
chose primary and they did not have the required GCSEs.
=> Show qualification required error correctly

config/environments/production.rb
The pen test raised that we are not generating https urls
Set `config.force_ssl` unless explicitly disabled (eg for running production environments locally)
=> Set force_ssl in production environments

config/environments/development.rb, config/environments/production.rb
GITPB-575
We specify a cookie name of `_dfe_session` in our cookie policy so that is the cookie we should be using
1. set the name of the cookie
2. Set the same_site setting to Lax
=> Use the name of the cookie we list in the cookie policy

app/models/wizard/steps/authenticate.rb, spec/models/wizard/steps/authenticate_spec.rb
[GITPB-684](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-684)
When an existing candidate successfully matches back to a contact in the CRM we populate the store with their existing details, including `candidate_id` and `qualification_id`. As we scope the information sent back to the API down to only the attributes of steps that weren't skipped - and `candidate_id`/`qualification_id` are not attributes of any step - the ids
weren't being sent back to the API.
This adds `candidate_id` and `qualification_id` to the `export` call on the `Authenticate` step and also ensures no answers to the `Authenticate` step will ever appear in the review answers view.
- Include matchback fields in export
=> Include matchback fields in export

app/models/teacher_training_adviser/steps/already_signed_up.rb, app/models/teacher_training_adviser/wizard.rb, app/views/teacher_training_adviser/steps/_already_signed_up.html.erb, spec/models/teacher_training_adviser/steps/already_signed_up_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb
[GITPB-658](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-658)
If a candidate has already signed up to the TTA service and successfully matches back, the store will contain a `true` value for `already_subscribed_to_teacher_training_adviser`. When this is the case, we will show them a new step that informs them they have already signed up and directs them to contact support if they think this incorrect.
- Prevent candidate from signing up multiple times
=> Prevent candidate from signing up multiple times

app/models/teacher_training_adviser/steps/have_a_degree.rb, app/models/teacher_training_adviser/steps/start_teacher_training.rb, spec/models/teacher_training_adviser/steps/have_a_degree_spec.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb
[GITPB-688](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-688)
It is currently possible for a user to miss a step; you can jump straight to the review answers step if you have the URL (though if you try and complete the submission it will redirect to the first invalid step).
If a candidate does this it causes an exception due to not expecting a non-skipped step to have a `nil` value (which happens if they manually plug a future step URL in). This commit updates the `reviewable_answers` to ensure an exception will never be raised, instead displaying an empty answer in the review answers step for any they have missed.
A better long-term solution may be to redirect to an invalid step if the candidate attempts to access a future step manually via …
=> Display review answers correctly when steps have been missed

Gemfile, Gemfile.lock, config/initializers/get_into_teaching_api_client.rb, spec/support/vcr.rb
This wraps the auto-generated API client and adds HTTP caching and retries.
=> Switch to Faraday API client

app/controllers/pages_controller.rb, spec/requests/pages_spec.rb
GITPB-681
As a user visiting a non existant page, I expect to see the "Page not found" screen rather than the "There has been an error" screen which is currently shown.
1. Show 404 page for missing templates
2. Added to request spec to check 
1. known pages are shown correctly
2. unknown pages are shown as a 404
=> Show 404 for unknown page template in pages controller

app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_review_answers.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
https://trello.com/c/lwbvOFRO/277-tta-flow-duplicate-ids
role="main" and id="main-content" have been incorrectly copied and pasted throughout the TTA flow and have been flagged in the DAC report as being problematic for screen reader users
there is a role main at the top level in the layout file, so this PR simply converts <main> tags to divs and removes the roles and ids which are not required
=> duplication of main role causing DAC failures

app/models/wizard/steps/authenticate.rb, spec/models/wizard/steps/authenticate_spec.rb
[GITPB-692](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-692)
When the wizard is about to be completed we check for any invalid steps; this was resulting in another API call to verify the verification code in the `Authenticate` step. If the user takes too long completing the form their code may not be valid by the time they reach they come to submit it, resulting in them being redirected back to the `Authenticate` step.
This PR sets an `authenticated` flag in the store; if this is present the `Authenticate` step will not try and re-verify their code.
- Prevent API check when already authenticated
=> Prevent API check when already authenticated

app/helpers/text_format_helper.rb, app/views/pages/privacy_policy.html.erb, spec/helpers/text_format_helper_spec.rb
[GITPB-590](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-590)
The privacy policy in the CRM has been updated to contain HTML for bullet points, anchor links, etc. We want this to be correctly rendered in the app.
- Format privacy policy with allowed HTML tags
=> Format privacy policy with allowed HTML tags

app/views/layouts/application.html.erb, spec/requests/beta_feedback_banner_spec.rb
Adds a feedback banner pointing to the Google form.
=> Add BETA feedback banner

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, spec/features/view_pages_spec.rb, spec/requests/pages_spec.rb
[GITPB-661](https://dfedigital.atlassian.net/browse/GITPB-661)
It has been decided the service will be called 'Get an adviser' - we need to change all references to reflect this.
- Rename service to Get an adviser
=> Rename service to Get an adviser

Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, app/webpacker/packs/application.js, config/environments/production.rb, config/initializers/csp.rb
[GITPB-678](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?selectedIssue=GITPB-678)
We want to make sure all cookies have the `secure` flag and an appropriate CSP is configured, along with other security headers flagged in the PEN test (x-content-type, x-xss-protection, x-frame-options).
- Enable secure cookies in production
- Configure CSP headers
Adds `SecureHeaders` gem for easily configuring CSP headers (Rails has this built in but the gem will prevent unsupported headers being sent if the browser doesn't support them, avoiding potential errors in dev).
CSP is basically locked down to self with inline styles allowed. Allows scripts from tracking pixel domains.
- Remove inline Javascript
It causes a CSP violation, so moving it into the main application.js.
=> Configure security headers

.env.preprod, .env.production, .env.rolling, .env.userresearch, config/initializers/secure_headers.rb
[GITPB-706](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?assignee=5e997e0e6b01320c41b6d21c&selectedIssue=GITPB-706)
If a CSP violation is triggered we want to report the violation to Sentry so that we will be notified/alerted.
- Send CSP violations to Sentry
- Rename `initializers/csp` to `initializers/secure_headers` as this file does more than just the CSP.
=> Send CSP violations to Sentry

Gemfile, Gemfile.lock, app/models/teacher_training_adviser/steps/date_of_birth.rb, spec/models/teacher_training_adviser/steps/date_of_birth_spec.rb
[GITPB-593](https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?assignee=5e997e0e6b01320c41b6d21c&selectedIssue=GITPB-593)
When a user enters an invalid date of birth we show them the same error as if they hadn't entered a value at all (and we also clear the date of birth field), which is confusing for users. Instead, we should show them a different error message that informs them they have entered an invalid date of birth.
- Custom error for invalid date of birth
Previously when an invalid `date_of_birth` was set we were showing the validation error associated with the `presence` validation (as we rescue and `nil` the `date_of_birth` if it can't be parsed as a `Date`).
Instead, this commit will add a custom error message when we rescue from an invalid date format and …
=> Custom error for invalid date of birth

app/models/teacher_training_adviser/steps/date_of_birth.rb
I had removed these as part of my refactoring, so they defaulted to the missing translation keys. This commit adds them back in.
=> Add validation error messages back in

config/initializers/secure_headers.rb
Enabling the various tracking pixels locally caused a bunch more CSP violations; this should quieten them.
Add support for running `webpack-dev-server` locally.
=> Various updates to the CSP

app/views/layouts/application.html.erb
They are not actually needed for private beta but are currently wrong so may
cause a problem in the future if they end up indexed now
Once we know all the urls these can be corrected properly
=> GITPB-585 Disable canonical links for now

app/helpers/application_helper.rb, app/views/teacher_training_adviser/steps/completed.html.erb, app/webpacker/controllers/analytics_base_controller.js
GITPB-683
We should be logging all page views on the TTA service to our analytics platforms
1. Change the sendEvent function to allow actions without events - needed for pinterest, per page views
2. Fire analytics events on all page views
3. Fire 'completed' events upon completion of the TTA flow 
1. Can be enabled by setting the appropriate env vars in `.env.local` - see here https://github.com/DFE-Digital/get-into-teaching-app/blob/master/.env.preprod - the env vars for pinterest, snapchat and facebook are the ones affected by this PR
=> GITPB-683 Add completion logging

app/helpers/application_helper.rb, app/models/teacher_training_adviser/steps/start_teacher_training.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb
Once it has passed the 17th September it is no longer possible to apply for teacher training for the current year.
=> Remove current year after 17th September

app/views/teacher_training_adviser/steps/completed.html.erb, app/webpacker/controllers/analytics_base_controller.js, app/webpacker/controllers/gtm_controller.js
GITPB-667
We should be firing a custom GTag conversion pixel upon completion of the wizard
1. Tweak to GTag code to allow firing custom events
2. Added custom event at end of wizard
=> Fire custom GTag event upon completion of wizard

app/helpers/application_helper.rb, app/models/teacher_training_adviser/steps/uk_or_overseas.rb, spec/models/teacher_training_adviser/steps/uk_or_overseas_spec.rb
We were previously looking for the country by its value; using the `id` should be more robust.
=> Set United Kingdom country by id

config/initializers/secure_headers.rb
GITPB-667
Twitter is loading analytics from more domains than initially thought.
1. Added more twitter domains to the Content Security Policy
=> GITPB-667 CSP Fixes for twitter pixels

app/webpacker/styles/application.scss
All links in the site are currently in the wrong colour. This is because they lack the `govuk-link` class
1. Set the `govuk-global-styles` variable to true - this merges in the `.govuk-link` class to the default `a` tag and `.govuk-body-m` class to the `p` tag
=> Fixed the default colour of all links

app/views/cookie_preferences/show.html.erb
There are a couple of missing words on the cookie preferences page
1. Add in the missing words
=> Fix for typo's on cookie preferences page

app/views/shared/_cookie_banner.html.erb
Currently the confirmation text shown, after accepting cookies in the banner, is white which is hard to see against the blue background.
1. Use <p> tags so it shows in black
=> Fix the text colour after accepting cookies from the banner

app/models/teacher_training_adviser/steps/subject_taught.rb, app/views/teacher_training_adviser/steps/_subject_taught.html.erb, spec/models/teacher_training_adviser/steps/subject_taught_spec.rb
We should not allow 'no preference' as an option for previous subject taught.
=> Remove No Preference from subject taught list

app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/unprocessable_entity.html.erb
Error pages (404, 500, etc) were not showing within the fixed width central column of the site
1. Added container class
2. Removed 2/3rds width restriction
=> Error pages were showing aligned to the left side of the screen

config/initializers/secure_headers.rb
In development we don't support SSL, so upgrading insecure requests has can have a strange knock-on behaviour that results in requests from Turbolinks being made multiple times.
=> Prevent insecure request upgrades in development

app/helpers/text_format_helper.rb, app/views/wizard/steps/_authenticate.html.erb, spec/helpers/text_format_helper_spec.rb
Avoids use of `html_safe` by running through `sanitize` with a whitelist of allowed tags.
=> Remove usage of html_safe

config/initializers/filter_parameter_logging.rb
We don't want to capture any personally identifiable information in our logs by accident.
=> Filter sensitive information from logs

config/initializers/secure_headers.rb
Allow GTM debugger.
Allow to run scripts from youtube (calls out to youtube.com/iframe_api).
=> Update CSP for GTM debugger

app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb
They are no longer booking a callback slot, so the copy has been updated to reflect that.
=> Update copy for overseas candidate callback

.env.preprod
Currently the Test (preprod) version points to the Prod (production) version of the GiT SIte. This is a product of moving the URLs from Test to Prod
1. Instead point to the Test version
=> Use correct URL for preprod git site

app/models/teacher_training_adviser/steps/overseas_country.rb, app/views/teacher_training_adviser/steps/_overseas_country.html.erb, spec/models/teacher_training_adviser/steps/overseas_country_spec.rb
The CRM contains an 'Unknown' country type - we don't want to display this to users in the overseas country step.
Refactors the logic to remove the United Kingdom country from the view into the model.
=> Remove unknown country from options

app/views/cookie_preferences/show.html.erb, app/views/pages/cookies.html.erb
The cookie policy was out of date with reality
1. Bring policy inline with reality
2. Added VWO cookie - this isn't actually set on this site but I've included it for consistency with the GiT site
=> Updated cookie policy to reflect current reality

app/controllers/healthchecks_controller.rb, spec/features/password_protection_spec.rb
We don't need to password protect the healthcheck endpoints
=> Bypass password for healthchecks

terraform/paas/application.tf, terraform/paas/domain.tf, terraform/paas/routes.tf, terraform/paas/test.env.tfvars
To enable Prometheus to scrape the metrics from each node of the adviser, internal routes are required.
The routes have had to be removed from the application.routes method and moved to routes.application.  Since there were now more resources it made sense to put routes into its own terraform file. (routes.tf)
=> Created internal routes for Prometheus

app/models/teacher_training_adviser/steps/subject_interested_teaching.rb, app/views/teacher_training_adviser/steps/_subject_interested_teaching.html.erb, spec/models/teacher_training_adviser/steps/subject_interested_teaching_spec.rb
We no longer want to allow the options 'No Preference' and 'Other' to be selected in response to the question "What subject would you like to teach?".
=> Remove No Preference and Other from SubjectInterestedTeaching step

app/models/healthcheck.rb, spec/models/healthcheck_spec.rb
The Api Client rescues errors and exposes them as an ApiError, we need to rescue on this as well as the underlying Faraday error.
=> Rescue on GetIntoTeachingApiClient::ApiError

Gemfile, Gemfile.lock, config.ru, config/application.rb, config/initializers/instrumentation.rb, config/initializers/prometheus.rb, lib/prometheus/metrics.rb, spec/lib/metrics_spec.rb, spec/requests/instrumentation_spec.rb
- Add Prometheus::Client
Add the Prometheus::Client for aggregating and exporting metrics on the /metrics endpoint.
Configured to use DirectFileStore as this supports Puma forking additional processes (by default metrics will be summed together; if we use a gauge metric this may not be desirable). The DirectFileStore is the recommended approach for applications with pre-fork servers/multi-processors, but there are caveats:
When scraped by Prometheus the store reads all the files into memory (one file per metric per process), which can bump up the memory usage a fair amount. I don't anticipate this being an issue for us yet/soon given the amount of metrics we're collecting is small.
The metric files need to be cleared out each time the application starts to avoid a new instance exporting …
=> Prometheus metrics

config/initializers/instrumentation.rb, lib/prometheus/metrics.rb, spec/lib/metrics_spec.rb, spec/requests/instrumentation_spec.rb
As we only have one Prometheus server scraping all apps we need to differentiate the metric names; adding "tta_" as the prefix to these metrics will enable us to find them in Grafana more easily and avoid clashes with other apps.
=> Prefix metrics with "tta_"

.github/workflows/production.yml
When releasing to Production we need to be able to re-release older versions. This means we need to pass in a tag.
However, we do not want to release tags that have not been tested so, we have a check that ensures a tag has been part of a release.
I have tested this by:
-  Commenting out all the code that does anything ( terraform, sentry and slack )
-  Running the action from the branch devops/workflows/pass-tag-in with a tag of "master" . As expected Failed
-  Running the action from the branch devops/workflows/pass-tag-in with a tag of "BETA-1.0". As expected Passed
-  Remove comments
=> Workflow Pass in Tags

app/models/concerns/api_options.rb, app/models/teacher_training_adviser/steps/overseas_country.rb, app/models/teacher_training_adviser/steps/stage_of_degree.rb, app/models/teacher_training_adviser/steps/start_teacher_training.rb, app/models/teacher_training_adviser/steps/subject_interested_teaching.rb, app/models/teacher_training_adviser/steps/subject_like_to_teach.rb, app/models/teacher_training_adviser/steps/subject_taught.rb, app/models/teacher_training_adviser/steps/what_degree_class.rb, app/models/teacher_training_adviser/steps/what_subject_degree.rb, app/views/teacher_training_adviser/steps/_gcse_maths_english.html.erb, app/views/teacher_training_adviser/steps/_gcse_science.html.erb, app/views/teacher_training_adviser/steps/_have_a_degree.html.erb, app/views/teacher_training_adviser/steps/_retake_gcse_maths_english.html.erb, app/views/teacher_training_adviser/steps/_retake_gcse_science.html.erb, app/views/teacher_training_adviser/steps/_stage_interested_teaching.html.erb, app/views/teacher_training_adviser/steps/_stage_of_degree.html.erb, app/views/teacher_training_adviser/steps/_subject_like_to_teach.html.erb, app/views/teacher_training_adviser/steps/_what_degree_class.html.erb, app/views/teacher_training_adviser/steps/_what_subject_degree.html.erb, spec/models/teacher_training_adviser/steps/overseas_country_spec.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb, spec/models/teacher_training_adviser/steps/subject_interested_teaching_spec.rb, spec/models/teacher_training_adviser/steps/subject_taught_spec.rb, spec/models/teacher_training_adviser/steps/what_degree_class_spec.rb, spec/models/teacher_training_adviser/steps/what_subject_degree_spec.rb, spec/support/shared_examples/wizard_support.rb
Some of the view partials were calling the API directly; instead we should go through the model.
General tidy up of view partials to make referencing step class consistent.
Minor refactoring of `ApiOptions` to make implementation and tests DRYer.
=> Remove API calls from view partials

app/views/teacher_training_adviser/steps/_what_subject_degree.html.erb, config/locales/en.yml
- Correct typo in error message
- Use entity value for both option value and name
On the `WhatSubjectDegree` step we send the text value of the subject instead of the GUID (which is unique to this step - the field expects a text value instead of ID).
=> Minor bug fixes after error message refactoring

spec/features/sign_up_spec.rb
A bug was introduced whereby the `WhatSubjectDegree` step was incorrectly persisting the GUID value of the subject instead of the text value.
This PR adds test coverage to the request payload sent in feature specs, to ensure the above scenario - along with other
potential bugs - are caught.
=> Verify request payload in feature specs

app/models/teacher_training_adviser/steps/gcse_maths_english.rb, app/models/teacher_training_adviser/steps/gcse_science.rb, app/models/teacher_training_adviser/steps/have_a_degree.rb, app/models/teacher_training_adviser/steps/what_degree_class.rb, app/models/teacher_training_adviser/steps/what_subject_degree.rb, app/views/teacher_training_adviser/steps/_have_a_degree.html.erb, config/locales/en.yml, spec/models/teacher_training_adviser/steps/gcse_maths_english_spec.rb, spec/models/teacher_training_adviser/steps/gcse_science_spec.rb, spec/models/teacher_training_adviser/steps/have_a_degree_spec.rb, spec/models/teacher_training_adviser/steps/no_degree_spec.rb, spec/models/teacher_training_adviser/steps/overseas_time_zone_spec.rb, spec/models/teacher_training_adviser/steps/stage_of_degree_spec.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb, spec/models/teacher_training_adviser/steps/what_degree_class_spec.rb, spec/models/teacher_training_adviser/steps/what_subject_degree_spec.rb
Improve naming of options to better match what is shown to the user.
Remove unused constants.
Remove redundant validation check for date being in the past; this is covered on the specs for the `years` method/inclusion validation.
=> Clean up HaveADegree step

config/locales/en.yml
Yaml was translating yes/no keys into `true` and `false`, which mean the translation key `have_a_degree.degree_options.yes` was not matching. By wrapping it in quotes YAML respects the yes/no key values.
=> Fix missing translation for HaveADegree step

app/models/teacher_training_adviser/steps/what_subject_degree.rb, spec/models/teacher_training_adviser/steps/what_subject_degree_spec.rb
We don't want to display the 'No Preference' option for teaching subjects in the `WhatSubjectDegree` step, as it doesn't make sense as an answer.
=> Remove 'No Preference' from WhatSubjectDegree step

app/models/teacher_training_adviser/steps/stage_interested_teaching.rb, spec/features/sign_up_spec.rb
N/a
We should be including the primary teaching subject as the preferred teaching subject id when submitting primary stage applicants to the API
1. This includes the expected primary subject in the export hash from the teaching stage. This only occurs if the teaching stage is skipped.
I've since thought of a better way of doing this but this approach is reliable and I can shift things around later on.
=> API requires the teaching subject set for primary applicants

app/controllers/csp_reports_controller.rb, config/initializers/instrumentation.rb, lib/prometheus/metrics.rb, spec/lib/metrics_spec.rb, spec/requests/csp_reports_spec.rb, spec/requests/instrumentation_spec.rb
[Trello-446](https://trello.com/c/SNNRS9VU/446-set-up-grafana-dashboard-for-csp-violations)
We currently send CSP violations to logit.io, which is fine for debugging/investigating a violation in detail, however it does not let us easily dashboard and aggregate violations in Grafana (we can't extract from the JSON payload).
- Instrument CSP violations
This commit instruments the CSP violations, sending them to our metrics database so that we can easily pull them out in Grafana to visualize/aggregate based on the collected labels:
- blocked_uri
- document_uri
- violated_directive
Lift and shift of https://github.com/DFE-Digital/get-into-teaching-app/pull/491
=> Instrument CSP violations

config/initializers/instrumentation.rb, spec/requests/instrumentation_spec.rb
The `violated-directive` of the CSP report sometimes comes through with more information that is useful for aggregating on:
``` violated-directive: img-src *.google.com *.gov.uk ```
Instead, we only care about the root directive/first token `img-src`. This will let us get a better breakdown of which CSP directives are being violated most frequently.
=> Take first token of violated-directive

config/initializers/instrumentation.rb, spec/requests/instrumentation_spec.rb
We are getting a lot of similar CSP violations where the blocked/document URIs only differ by their query string parameters, for example:
```
https://t.co/i/adsct?type=javascript&version=1.1.0&p_id=Twitter&p_user_id=0&txn_id=o0wo4&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0&tw_iframe_status=0&tw_document_href=https%3A%2F%2Fbeta-getintoteaching.education.gov.uk%2Fsteps-to-become-a-teacher
https://t.co/i/adsct?type=javascript&version=1.1.0&p_id=Twitter&p_user_id=0&txn_id=o0wo4&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0&tw_iframe_status=0&tw_document_href=https%3A%2F%2Fbeta-getintoteaching.education.gov.uk%2Fsteps-to-become-a-teacher%23step-4
```
If we truncate the query parameters it will let us aggregate on the …
=> Strip query params from document/blocked URIs

config/initializers/instrumentation.rb, spec/requests/instrumentation_spec.rb
Using the path as the label (removing the hostname, which is always the same for this attribute) makes the visualisation nicer in Grafana.
=> Extract path from document_uri

app/controllers/application_controller.rb, app/controllers/concerns/wizard_steps.rb, spec/requests/sign_up_spec.rb
We currently fail with a 500 error if the wizard is initialised with an unknown step; this happens if the user enters a bad URL, so it would make more sense to return a 404 in this scenario.
=> Render 404 on Wizard::UnknownStep

app/views/pages/cookies.html.erb
The GA cookie we are listing is not correct, this updates it to match what we are using in production.
=> Update GA cookie name

config/webpacker.yml, package.json
Webpacker is throwing a deprecation warning as `resolved_paths` has now been replaced with `additional_paths`.
=> Fix webpacker deprecation warning

config/initializers/instrumentation.rb, spec/requests/instrumentation_spec.rb
Aggregating the metrics on path doesn't provide a good insight at present due to the query parameters being included in the path. By removing the query parameters we can aggregate on the underlying path/action.
Similarly, the view metrics contain the absolute path to the views directory which makes displaying them in a table awkward. Removing the `/path/to/app/views/` prefix leaves us with the template identifier.
=> Sanitize metrics for better aggregation

app/controllers/application_controller.rb, app/models/wizard/issue_verification_code.rb, app/views/errors/too_many_requests.html.erb, config/initializers/rack_attack.rb, spec/requests/rate_limiting_spec.rb, spec/requests/sign_up_spec.rb, spec/support/shared_examples/rate_limiting_support.rb, spec/support/shared_examples/wizard_support.rb
[Trello-352](https://trello.com/c/MjWfjLi7/352-set-rate-limiting-on-api)
The API is rate limited to 30 requests/client API key/minute for transactional/vulnerable endpoints (both apps currently share the same API key, but this will change in the future).
We want to apply per-user/IP rate limiting in the front end applications as well, to add more granular control over submissions. The rate limits initially will be 5 requests/IP/minute - this should be plenty for now, but may need tweaking as we roll out to more users (or to take into account advertising 'spikes' in traffic).
When a user encounters a rate limit we want to display a 429 error page similar to the existing 404/500 error pages.
If the user encounters an API rate limit we want to display the same page.
- Rate limit transaction …
=> Rate limit transactions

config/environments/preprod.rb, config/environments/rolling.rb, config/environments/userresearch.rb
We want to disable rate limiting in production-like environments (but not production) so that the integration tests can be ran successfully.
=> Disable rate limiting in production-like environments

app/models/teacher_training_adviser/steps/uk_callback.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb
[Trello-518](https://trello.com/c/oaWXG1mL/518-fix-sentry-issue-in-tta)
[Sentry](https://sentry.io/organizations/dfe-bat/issues/2006318159/?project=5276960&referrer=slack)
If a user proceeds through the TTA sign up as a candidate with an equivalent degree that is located in the UK, but then manually enters the URL for the review answers page before completing the `UkCallback` step an error would be thrown as the `phone_call_scheduled_at` is `nil` and we try and call `to_date` on it.
- Prevent error when skipping ahead to review answers step
Update to use the safe navigation operator on `phone_call_scheduled_at`.
=> Prevent error when skipping ahead to review answers step

spec/requests/review_answers_spec.rb
A user is able to skip straight to the review answers page manually by entering the correct URL without actually completing any steps. This is expected behaviour, however we need to ensure the steps can handle this scenario and don't assume they have been answered when their `reviewable_answers` method is called.
Add test to simulate rendering all wizard steps for review as unanswered.
=> Add test coverage for reviewing incomplete steps

app/views/pages/cookies.html.erb
Rename 'None functional' to 'Non-functional'
=> Correct typo in cookie policy

app/controllers/concerns/wizard_steps.rb, spec/requests/sign_up_spec.rb
If a candidate's session expires (so they sit on the authenticate step overnight, for instance) then they hit the link to resend their verification code the app attempts to make an invalid request to the API (email, first and last name are nil). This currently results in a 500 error for the user. Instead, we rescue this condition and redirect to the identity step so that they can re-authenticate.
Fixes https://sentry.io/organizations/dfe-bat/issues/2010050592/?project=5276960&referrer=slack
=> Redirect to identity step on resend_verification bad request

.github/workflows/build.yml, Gemfile, Gemfile.lock, sonar-project.properties
- Update SonarCloud to know where Rubocop results are
- Direct SonarCloud to simplecov output
- Revert SimpleCov version for SonarCloud compatibility
Lift & shift of https://github.com/DFE-Digital/get-into-teaching-app/pull/532
=> Fix SonarCloud integration

app/helpers/application_helper.rb, app/views/cookie_preferences/show.html.erb, app/webpacker/controllers/cookie_preferences_controller.js, app/webpacker/styles/application.scss, spec/helpers/application_helper_spec.rb, spec/javascript/controllers/cookie_preferences_controller_spec.js
The cookie preferences should require the user to save their preferences rather than auto-saving changes
1. Add a save buttom
2. Added a back link which will trigger a page reload
3. Replaced existing back link with one which will reload the page
=> Added a save button to the Cookie Preferences page

Dockerfile
https://trello.com/c/O9T3Qco5
We are using the `--without` bundler option but this has now been deprecated
1. Switch to using the env var replacement
2. Removed the unused sassc compillation option
=> Replaced usage of deprecated bundler option

app/models/teacher_training_adviser/steps/accept_privacy_policy.rb, app/validators/policy_validator.rb, spec/models/teacher_training_adviser/steps/accept_privacy_policy_spec.rb, spec/validators/policy_validator_spec.rb
We don't need to pass the `method:` into this validator as it always calls `get_privavcy_policy`.
Only rescue on 400/bad request; this indicates the policy entered does not exist in the system. Other errors will bubble up to show the respective error page to the user.
=> Simplify PolicyValidator

.github/PULL_REQUEST_TEMPLATE.md
N/a
Currently the template references JIRA instead of Trello
1. Reference trello instead
=> Updated Pull Request template - we are now using Trello

.github/workflows/new_deploy.yml
Trial workflow needs to be correct name in master or it cannot be picked up by the preceding workflow, even though it isn't running on the master branch
[Continuous Deployment](https://trello.com/c/UQrm3g59/516-continuous-deployment)
Workflow needs to exist in master for the system to even consider working on branches
This is a single file that should not effect anything, it isn't fully working but because of how github works, it is a place holder.
=> Renamed Workflow

.github/workflows/deploy.yml
When the Deployment is run we can pick up the secrets required depending on the Environment passed in, so this allows us to move to a single deployment script for all environments, just called from a different calling thread depending on the trigger
=> Added Conditional Variables on Deploy

spec/spec_helper.rb
We want to prevent deprecation warnings creeping into the codebase
1. Enable the RSpec option to raise errors when it encounters a deprecation warning
=> Raise errors in specs for deprecation warnings

app/helpers/application_helper.rb, app/models/concerns/api_options.rb, app/models/teacher_training_adviser/steps/subject_like_to_teach.rb, app/models/teacher_training_adviser/steps/subject_not_found.rb, app/models/teacher_training_adviser/wizard.rb, app/views/teacher_training_adviser/steps/_subject_like_to_teach.html.erb, app/views/teacher_training_adviser/steps/_subject_not_found.html.erb, config/locales/en.yml, spec/features/sign_up_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/teacher_training_adviser/steps/subject_like_to_teach_spec.rb, spec/models/teacher_training_adviser/steps/subject_not_found_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb, spec/support/shared_examples/wizard_support.rb
[Trello-564](https://trello.com/c/w3emKbaL/564-on-returners-step-5-of-tta-service-amend-cant-see-my-subject-and-include-better-cta)
We want to improve the visibility of the "Can't see the subject you would like to teach?" prompt by changing it to a radio button. If selected, we should take the candidate to a new page with improved copy and calls to action.
Add GiT link helpers for events/mailing list
We need to be able to link to the mailing list and events as CTAs, this adds convenience helpers.
- Improve user experience when SubjectLikeToTeach is not found
Change the "Can't see the subject you would like to teach?" prompt to be an extra radio button on the "What subject would you like to teach if you return to teaching?" question.
Add an additional step to handle when the user selects …
=> Improve user experience when SubjectLikeToTeach is not found

app/views/teacher_training_adviser/steps/_subject_not_found.html.erb
Correct the CTA link to go to the events page
=> Fix event CTA link when subject not found

.github/workflows/build.yml
The Github.sha reference fails in the pipline with not found.
This is probably caused by the merge and we really need to be
using the master branch
=> bugfix Using refs/heads/master not github.sha

.github/workflows/build.yml
Only the SHA is required on the deployment, the release_tag is not
required in the normal workflow running
=> SHA Required on Deploy

.env.production, app/helpers/application_helper.rb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb, app/webpacker/controllers/image_pixel_base_controller.js, app/webpacker/controllers/lid_controller.js, config/initializers/secure_headers.rb, spec/helpers/application_helper_spec.rb, spec/javascript/controllers/lid_controller_spec.js, spec/requests/lid_tracking_pixels_spec.rb, spec/support/matchers/analytics_matcher.rb
[Trello-314](https://trello.com/c/8PmnT4DD/314-development-add-lid-pixels-to-pages-for-audio-advertising)
Lift & shift of https://github.com/DFE-Digital/get-into-teaching-app/pull/602
- Add LID tracking pixel controller
- Enable LID tracking pixels in production
- Allow LID pixel in CSP
- Fire LID tracking pixel on home page & sign up completion
=> Add LID tracking pixel

app/controllers/healthchecks_controller.rb, spec/requests/healthchecks_controller_spec.rb
[Trello-355](https://trello.com/c/ADNV86cu/355-development-log-healthchecks)
Logging out the health check response will assist with debugging if the app goes offline.
- Log out health check responses
=> Log out health check responses

app/models/teacher_training_adviser/steps/returning_teacher.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/returning_teacher_spec.rb
By defaulting this in the app we have an edge case where a candidate proceeds as a returner then backs out and starts the new candidate journey. If they do this we will pre-fill the secondary education phase (as its defaulted when they selected returner).
Instead, we will default this value in the API so there is no need to set it for returners at all in the app.
=> Don't default preferred education phase for returners

.github/workflows/build.yml
On the Production deployment job the Release reference has not been populated, this seems to be because it is populated in the development job, and although the production job does not 'need' the development job directly, I think it cannot access the variables without the job being added.
=> Production needs cypress and development

.github/workflows/build.yml
When you create a draft release, it does not come back from the API. so I need to create the release as a full release.
=> Draft Releases Do not work, changed to full

config/initializers/rack_attack.rb
According to the Rack::Attack docs we should be returning an array of strings here.
=> Fix Rack::Attack exception

app/models/teacher_training_adviser/steps/returning_teacher.rb, spec/models/teacher_training_adviser/steps/returning_teacher_spec.rb
This was previously needed to default the `preferred_education_phase_id` to secondary when they are a returning teacher. This logic was moved to the API and subsequently removed from the app by PR #413 but the attribute was left in. This causes a bug when the user:
- Starts down the non-returner path
- Selects Primary as their education phase
- Backs out and goes down the returner path
- Completes the wizard
The `preferred_education_phase_id` is then submitted to the API as Primary (exported from the `ReturningTeacher` step) when it shouldn't be sent at all, as we default the value in the API now.
=> Remove redundant attribute from ReturningTeacher step

app/views/teacher_training_adviser/steps/completed.html.erb
We want the feedback link to go to the same Google form as the main website, not GOV.uk. Also updates the link to open in a new page.
=> Update feedback link

.github/workflows/build.yml
When sending the review failure notification the name of the project
is not being displayed, because a $ was missing in the text.
=> Bug Fix - Display Error in Workflow Error Message

.github/workflows/build.yml
The default time out on action-wait-for-check is only 600 seconds
but the current time to run the tests is about 1400 seconds. so
increased to 1800, giving a bit of slack for slow days
=> Bug Fix - Time out waiting for Tests

.github/workflows/build.yml
When the review process is ready the developers do not want to see a message is slack telling them the Review is ready.
Similarly when a release to production has been completed the message is not needed.
Remove the slack notification calls
No special requirements
=> Enhancement - Do not issue slack notifications

.github/workflows/build.yml
When a PR has more than one line of text, the first line is the only line sent to the Release.
This change should allow mulit-line YAML and thus permit larger comments to be transferred over.
=> Muliti line Release Notes only pick first line

app/models/teacher_training_adviser/steps/stage_interested_teaching.rb, spec/features/sign_up_spec.rb
If a candidate selects their preferred education phase to be 'primary' we should also be setting their preferred teaching subject to 'primary'. This is already done in the API, so its no longer necessary to default it in the app:
https://github.com/DFE-Digital/get-into-teaching-api/blob/master/GetIntoTeachingApi/Models/TeacherTrainingAdviserSignUp.cs#L177-L185
=> Remove logic to default the preferred_teaching_subject_id

Gemfile.lock
Bumps the API client version, which will remove the HTTP cache monkey patch; instead the API should now be returning correct HTTP caching headers allowing the response to be cached privately for 5 minutes (which Faraday should automatically adhere to).
=> Bump API Client to remove HTTP cache monkey patch

.github/workflows/build.yml
sometimes the message does not contain the regex used to find the PR. This causes a problem with no release tag.
So creating a date based tag until a solution can be found
=> Duplicate release tag

.github/workflows/build.yml
The developers want to be able to see what releases are published on SLACK
Step 1. Set the release to draft when first created and then when
the application is deployed then the release can be published
=> Publish release

.github/workflows/build.yml
When a new release goes out to Production, we should tag the notes attached to that Release and publish them to the slack channel to publicise the release
=> Inform Slack of Release

Gemfile.lock
The types are being deprecated and support has been removed from the API client. This updates the client in the app to ensure nobody accidentally references the old type methods going forward (they will be deleted from the API shortly).
=> Update API client to remove types

app/controllers/concerns/wizard_steps.rb, app/models/wizard/base.rb, app/models/wizard/step.rb, app/views/teacher_training_adviser/steps/_form.html.erb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb, spec/models/wizard/base_spec.rb, spec/models/wizard/step_spec.rb, spec/requests/sign_up_spec.rb
https://sentry.io/organizations/dfe-bat/issues/1864908606/?project=5276960&query=is%3Aunresolved
Currently it is possible for a candidate to hit a 'dead end' and then manually skip to the review answers screen (which they may have open in another tab) and attempt to complete the sign up, which will result in a 500 error.
This is possible because we currently only check that all 'active' (non-skipped) steps are _valid_, but we neglect to check if they are a 'dead end' step themselves. An example of this would be:
- Returning candidate selects 'Other' as the subject they would like to teach, which is stored as `-1` in the `preferred_teaching_subject_id` attribute (and valid, otherwise they would not to the 'Get support' step).
- Candidate is presented with the 'Get support' dead-end step.
- …
=> Prevent sign up completion when a 'dead end' step was encountered

.github/workflows/trello.yml
https://trello.com/c/2CUilw5w
When a PR is opened with a link to the associate Trello card, automatically add a comment to the Trello card with the associate Pull Request
1. Create a comment in the trello card with a link to back to the PR
=> Link GitHub PRs to Trello tickets automatically

.github/workflows/deploy.yml
Set the Deploy timeout to 30 minutes
When a deployment takes longer than 30 minutes stop the deployment.
=> Increase Deploy Timeout

config/initializers/formbuilder.rb, spec/features/sign_up_spec.rb
N/A (Accessibility check feedback)
The form builder wraps fieldsets in only a `<legend>` tag by default, to force it to render a `<h1>` either the `tag:` param must be set or the default configured via an initializer.
Add a default `h1` tag to for legends in a new formbuilder initializer and update specs accordingly. Could possibly be tidied further by adding a custom `have_header` matcher.
Are there any pages with more than one fieldset? I couldn't find any at a cursory glance.
=> Change formbuilder default legend tag to h1

app/webpacker/styles/application.scss
[Trello-724](https://trello.com/c/SDLkj67Z/724-add-css-for-the-turbolinks-progress-bar)
Add CSS to style the Turbolinks progress indicator, using the GiT blue for the background colour.
- Show Turbolinks progress indicator
=> Show Turbolinks progress indicator

Gemfile.lock, app/views/teacher_training_adviser/steps/_date_of_birth.html.erb, app/views/teacher_training_adviser/steps/_have_a_degree.html.erb, app/views/teacher_training_adviser/steps/_overseas_telephone.html.erb, app/views/teacher_training_adviser/steps/_returning_teacher.html.erb, app/views/teacher_training_adviser/steps/_stage_interested_teaching.html.erb, app/views/teacher_training_adviser/steps/_uk_telephone.html.erb, app/views/teacher_training_adviser/steps/_what_subject_degree.html.erb, app/views/wizard/steps/_authenticate.html.erb, config/initializers/formbuilder.rb, spec/features/sign_up_spec.rb
Upgrade to the latest version of `govuk_design_system_formbuilder`. The only required change here is to change the hint arg format from `hint_text: "blah"` to `hint: { text: "blah" }`, which makes it more consistent with labels and legends.
Closes #346
=> Upgrade to govuk design system formbuilder 2.1.1

terraform/paas/production.env.tfvars
Now that the old statuscake instances have been cleaned up it is possible to restart the new instances
=> reintroduce statuscake on terraform

.github/workflows/build.yml
when Dependabot creates a PR, it still goes to Review ( thats good) but it does not need a Myles review. so prevent the label being added
I tried `if: ! contains(github.event.pull_request.user.login, ‘dependabot’) ` and github hated it so stuck to`if: contains(github.event.pull_request.user.login, ‘dependabot’) == false`
=> ignore dependabot labels

app/views/teacher_training_adviser/steps/_date_of_birth.html.erb
Following GDS assessment, we were asked about why we collect DoB information. This help text addresses this query.
Added line: We use this information to confirm you are aged 18 or over.
Does this render okay?
=> Add help text on why we check Date of Birth

terraform/paas/variables.tf
[Rename GovPaaS Organisation](https://trello.com/c/T6s07KQ9/759-as-the-usage-of-paas-in-dfe-is-growing-and-we-need-to-scale-up-governance-and-tools-it-was-decided-to-move-to-a-simpler-model-wi)
As the usage of paas in DfE is growing and we need to scale up governance and tools, it was decided to move to a simpler model with a single organisation instead of the 3 we have today. To this effect, dfe-teacher-services will be renamed to dfe and become the single organisation.
=> Rename GovPaaS Organisation

app/helpers/application_helper.rb, app/views/teacher_training_adviser/steps/_subject_not_found.html.erb, spec/helpers/application_helper_spec.rb
[709](https://trello.com/c/JCsVtsGK/709-update-content-in-dead-end-for-returner-tta-flow-to-better-reflect-support-options)
Minor rewording of the page required
In addition to the rewording, now we're linking to a particular kind of event, the `#link_to_git_events` helper has been amended with a `events_path:` param that, in this case, allows us to link directly to `/events/category/online-events`.
Is the change to the helper sensible? I thought above creating a generic `#link_to_git_page` helper and then using it as the basis for the other `#link_to_git...` methods, but went for low-impact for the time being.
=> Update subject not found dead end copy

app/views/teacher_training_adviser/steps/_identity.html.erb, config/locales/en.yml, spec/features/sign_up_spec.rb
https://trello.com/c/V9okgwUp/740-content-change-surname-to-last-name-in-sign-up-forms
Change the labels from 'Surname' to 'Last name'.
This was highlighted in the DAC report, surname is slightly less culturally-sensitive than last name. This still doesn't fall in line
with [GOV.UK's recommendation](https://design-system.service.gov.uk/patterns/names/) of asking for a full name but they need to be separate in order to placate the CRM.
=> Change surname to 'last name' throughout

.github/workflows/build.yml
We don't use the Review Apps to verify dependabot branches so we don't need to create them
1. Don't create review apps if branch name starts with 'dependabot/'
=> Don't create review apps for dependabot branches

.github/workflows/build.yml
https://trello.com/c/Ueda1EDd/640-release-notes-are-only-first-line
The release is only created with the first line of the PR, I want to improve this to provide the full PR Body
Create a MD file and use that to create the release
This will not effect the product
This should not make any effect to the SLACK output, that will come later
=> Better Release Body

.github/workflows/build.yml
[Artefacts Missing](https://trello.com/c/T9VjNdeY/751-rubocop-no-artifacts-will-be-uploaded)
The Rubocop test results artefact was not being kept.
There are no code changes
=> RubyCop Artefact Missing

Gemfile.lock, app/models/teacher_training_adviser/steps/authenticate.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/authenticate_spec.rb
[Trello-776](https://trello.com/c/HILK0xws/776-mailing-list-sign-up-process-for-crm-data-migration)
The existing methods/endpoints to exchange an access token for a pre-filled TTA sign up model are being deprecated and removed. This commit transitions the codebase to use the new `exchange_access_token` method.
- Swap to new token exchange methods/endpoints
I've manually tested a match back TTA sign up.
=> Swap to new token exchange methods/endpoints

Gemfile.lock
Changes the way `DateTime` is formatted to fix a bug on TTA sign up when scheduling a phone call (it was serializing in the incorrect format).
=> Fix incorrect serialisation of `DateTime`

.env.preprod, .env.rolling, config/environments/preprod.rb, config/environments/rolling.rb, config/initializers/rack_attack.rb
Bots poking around the site should be banned
1. Added Fail2Ban configuration - this is configured with an environment variable `FAIL2BAN` which is an integer of the minutes to ban an ip for. The rule automatically bans any IP accessing a question able endpoint - ie wordpress or php files or etc/passwd
2. Enable FAIL2BAN for 1 minute in `rolling` for quick testing (eg the Review URLs
3. Enable FAIL2BAN for 3 minutes in `preprod` / aka staging
4. Enabled Rack::Attack in all environments, instead disabling only the req limits in `preprod` / aka staging - to allow for the cypress tests
5. Log to Sentry when an IP is blocked and for how long
This PR does not enable the checks in production yet
=> Add Fail2ban to Rack::Attack config

app/controllers/teacher_training_adviser/steps_controller.rb, app/models/teacher_training_adviser/steps/has_teacher_id.rb, app/models/teacher_training_adviser/steps/overseas_telephone.rb, app/models/teacher_training_adviser/steps/previous_teacher_id.rb, app/models/teacher_training_adviser/steps/uk_telephone.rb, app/models/wizard/base.rb, app/models/wizard/step.rb, app/models/wizard/steps/authenticate.rb, app/models/wizard/store.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/has_teacher_id_spec.rb, spec/models/teacher_training_adviser/steps/overseas_telephone_spec.rb, spec/models/teacher_training_adviser/steps/previous_teacher_id_spec.rb, spec/models/teacher_training_adviser/steps/uk_telephone_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb, spec/models/wizard/base_spec.rb, spec/models/wizard/step_spec.rb, spec/models/wizard/store_spec.rb, spec/support/shared_examples/wizard_support.rb
This is a lift and shift of the app PR https://github.com/DFE-Digital/get-into-teaching-app/pull/907
- Add crm data support to store
We want to hide steps that are optional and have been pre-filled with candidate information.
In order to determine if a step can be pre-filled from the CRM we need to retain the CRM values in the store so that they
can later be queried independently of the data written by the app.
The `fetch` method has also been updated to return values for all keys passed in; this makes the logic to determine if all
values are present in a store simpler (otherwise we would also have to check the `count` to ensure all values are present):
```
fetch(%[...], source: :crm).values.all(&:present?)
```
- Add support for optional steps
An optional step will be skipped if (and only …
=> Hide pre-filled optional fields and steps

.github/workflows/build.yml, .github/workflows/manual.yml
[Release Notes are only first line](https://trello.com/c/Ueda1EDd/640-release-notes-are-only-first-line)
When SLACK outputs a Release Note, it only presents the first line of the text, this is not adequate
Change the github action to use Powershell and return a json string
No change to  application
=> Improve Release Note

.github/workflows/build.yml
SONAR-TOKEN is trying to be retrieved from GITHUB, but it no longer exists there. this causes the Sonarcube analysis to fail, stopping the pipeline
Retrieve SONAR-TOKEN from Azure
This does not impact the application
=> Left github secret in

Gemfile.lock, app/models/teacher_training_adviser/steps/returning_teacher.rb, app/models/teacher_training_adviser/steps/stage_interested_teaching.rb, app/views/teacher_training_adviser/steps/_returning_teacher.html.erb, config/locales/en.yml, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/has_teacher_id_spec.rb, spec/models/teacher_training_adviser/steps/have_a_degree_spec.rb, spec/models/teacher_training_adviser/steps/returning_teacher_spec.rb, spec/models/teacher_training_adviser/steps/review_answers_spec.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb, spec/models/teacher_training_adviser/steps/subject_like_to_teach_spec.rb, spec/models/teacher_training_adviser/steps/subject_not_found_spec.rb, spec/models/teacher_training_adviser/steps/subject_taught_spec.rb, spec/vcr/https_/get-into-teaching-api-dev_london_cloudapps_digital/api/pick_list_items/candidate/types.yml
[Trello-1343](https://trello.com/c/FLYEKcpU/1343-improve-how-we-check-for-returning-teachers)
We currently do not send to the API if the candidate is a returning teacher vs interested in teaching. This means the logic to determine if a candidate is a returner in the API is a bit convoluted. The API now supports sending the candidate type explicitly, which will mean we can clean that logic up and also has the benefit of being able to pre-fill the "Are you returning to teaching?" step in the TTA service.
- Update API client to include typd_id
- Update ReturningTeacher step to send type_id
In the past we haven't sent a specific attribute value in response to the `ReturningTeacher` step (the previous `returning_to_teaching` attribute was transient and only used to control the flow of the …
=> Explicitly send the candidate type_id on sign up

app/models/teacher_training_adviser/steps/overseas_time_zone.rb, app/models/teacher_training_adviser/steps/uk_callback.rb, spec/models/teacher_training_adviser/steps/overseas_time_zone_spec.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb
[Trello-1369](https://trello.com/c/ZxF0ggqO/1369-telephone-not-visible-in-review-answers-page-when-equivalent-uk-based-candidate-books-callback)
The telephone field when filled in as part of the `OverseasTimezone` step was not presented under the personal details section; its now correctly located.
The `UkCallback` step has a mixture of personal/non-personal details and was only showing the non-personal (callback date/time) - it has been updated to render the telephone as well and the answers have been shifted into the personal details section.
Going forward it would make sense to split telephone/callback details into their own section perhaps (instead of trying to split a single steps answers across multiple sections when it contains a mixture of personal/non-personal details).
- Show …
=> Show telephone field on review answers step

.gitignore, Gemfile.lock, app/controllers/concerns/circuit_breaker.rb, app/controllers/concerns/wizard_steps.rb, app/controllers/teacher_training_adviser/steps_controller.rb, app/views/teacher_training_adviser/not_available.html.erb, config/routes.rb, spec/requests/circuit_breaker_spec.rb
https://trello.com/c/e9vBMLJE
When repeated API failures occur, circuit breaker middleware in the Ruby client will raise a GetIntoTeachingApiClient::CircuitBrokenError. This is an attempt to reduce the impact of any future service failures.
- Redirect to service unavailable page when there is a GetIntoTeachingApiClient::CircuitBrokenError
=> Circuit breaker redirect

.gitignore, Makefile
[Provide Method to Assist Developers with Secrets](https://trello.com/c/qqFKSJo6/1385-provide-method-to-assist-developers-with-secrets)
The DevOps team want the Developers to handle the Azure secrets in a standard way, and want to provide tooling to support this.
Makefile added which provided commands to manage secrets
No changes to Application or Delivery
=> Added Secrets Makefile

Gemfile, Gemfile.lock, config/initializers/exclude_cloudfront_ips.rb, lib/cloud_front_ip_filter.rb, spec/lib/cloud_front_ip_filter_spec.rb
We current (incorrectly) treat the IP address of the CloudFront proxy as the legitimate address of the request client. This is probably causing incorrect behaviour in the request throttling behaviour.
It is definitely breaking the Fail2ban behaviour, though that is not currently turned on in production - because of this issue.
1. Replace the `Rack::Request.ip_filter` proc with a class (which responds to `call`) - that in turn checks against the original `ip_filter` plus the list of ip addresses provided by the `actionpack-cloudfront` gem. That gem in turn will download the list from amazon's JSON endpoint on boot, and fall back to a static copy of the file included in the gem.
This is a difficult one to test prior to it reaching production? Hence the monkey …
=> Ignore cloudfront IPs

.env.rolling, config/initializers/rack_attack.rb
We now know that Fail2ban is working correctly so remove the debug data prior to deployment to production
1. Disable in DEV environment (`Rails.env.rolling?`) because this is getting triggered by the OWASP scan
2. Remove the debug data from the message raised in sentry when we ban someone
=> Removed debug data from ban message and disable fail2ban on DEV servers

Gemfile.lock
The API client had deprecation warnings for Ruby 2.7; these have since been fixed, so updating the app to pull in the new version.
I gave this a quick smoke test locally and it all seems fine.
=> Bump API client to fix deprecation warnings

app/models/teacher_training_adviser/steps/uk_callback.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb
[Trello-1405](https://trello.com/c/Ccwvwt0v/1405-bug-fix-no-degree-step-can-be-incorrectly-shown-on-returner-journey)
If a candidate goes all the way through the equivalent degree/UK path and schedules a phone call, then edits the answer for 'are you returning to teaching' and proceeds down the returner path as a UK candidate we end up exporting their `phone_call_scheduled_at` value incorrectly and the request fails the API validation.
Instead, we should treat the `UkCallback` step as `skipped?` unless they are shown the `HaveADegree` step.
- Bug fix callback scheduled for returner
=> Bug fix callback scheduled for returner

Gemfile.lock, app/controllers/application_controller.rb, spec/requests/api_client_request_id.rb
[Trello-1412](https://trello.com/c/65tZmUeb/1412-add-correlation-ids-to-rails-apps-and-api)
The `GetIntoTeachingApiClient` is configured to pick up on a `request_id` set on `Thread.current` (indirectly via `ActiveSupport::CurrentAttributes`). This PR updates the app to set the Rails `request_id` on `GetIntoTeachingApiClient::Current` so it gets sent as part of all requests to the API.
- Forward request_id to the API
=> Forward request_id to the API

config/initializers/get_into_teaching_api_client.rb
https://trello.com/c/e9vBMLJE
Circuit breaker middleware has been added to the API Client Gem. It is enabled via the following configuration:
```rb
GetIntoTeachingApiClient.configure do |config|
config.circuit_breaker = {
enabled: true, # Enables the circuit breaker middleware
threshold: 5, # Number of failures that will cause the circuit breaker to trip
timeout: 5.minutes # Amount of time until the circuit breaker will attempt to recover
}
end
```
- Enable circuit breaker
=> Enable circuit breaker

config/initializers/exclude_cloudfront_ips.rb
Enable cloudfront IP filtering in all environments.
1. Only exclude cloudfront ip filtering in Dev and Test environments
This matches the behaviour of the actionpack-cloudfront gem
=> Enable CloudFront IP filtering in production

.env.production
We want to discourage attack bots from scanning the site - this change will do a crude identification and ban bots accordingly.
The actual identification logic may need to be exanded in the future.
Enable Fail2Ban in production
For now its only being enabled for the minimum timeframe - ie 1 minute
=> Enable Fail2Ban in production

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/rack_attack.rb, config/initializers/sentry.rb, spec/requests/invalid_authenticity_token_spec.rb
The `sentry-raven` gem we were using is deprecated/in maintenance mode. Sentry now have two gems that replace it (`sentry-ruby` and `sentry-rails`).
Update to new gems and migrate existing code (migration guide: https://docs.sentry.io/platforms/ruby/guides/rails/migration/)
The `Sentry::BackgroundWorker` sends events to Sentry async by default, using `ActiveRecord::Base.connection_pool`. We don't use `ActiveRecord` in the app, so this was failing silently with an `unrecognized constant ActiveRecord`. Instead of pulling in `ActiveRecord` just for this (which has its own difficulties as it tries to connect to a DB by default) we override the `async` handler to just send everything synchronously (which is how `sentry-raven` was working).
=> Update Sentry gem

app/models/teacher_training_adviser/steps/no_degree.rb, spec/models/teacher_training_adviser/steps/no_degree_spec.rb
[Trello-1405](https://trello.com/c/Ccwvwt0v/1405-bug-fix-no-degree-step-can-be-incorrectly-shown-on-returner-journey)
If a candidate initially starts their journey as a non-returner and then selects no degree we will show them the exit step informing them that they have to have a degree.
If they they go back and try to carry on as a returner they will see the same exit step. Instead, we should be ignoring their selected degree option when on the returner journey.
- Fix bug where NoDegree step is shown incorrectly
=> Fix bug where NoDegree step is shown incorrectly

.github/workflows/build.yml
[Keep Lint Failure Outputs ](https://trello.com/c/C2jiSt2r/1394-keep-lint-failure-output)
When a LINT fails the following step to save  the results does not run, changed the process to always try to save the results.
added ``` If: failure() ```
No changes to the application
=> Keep Artefacts Even on Failure

Gemfile, Gemfile.lock
It looks like we used to use this, probably before the API endpoint to get countries was available. There's no reference to it now so removing.
=> Remove country_select gem

Gemfile.lock, config/initializers/sentry.rb
Sentry has now removed its dependency on ActiveRecord so it works out of the box (we don't need the custom async handler).
=> Bump sentry-rails from 4.3.0 to 4.3.1

.github/workflows/build.yml, spec/spec_helper.rb
https://trello.com/c/gabkUApE
Simplecov is now capable of generating an 'official' json output - Sonarcloud should be using that instead of relying on the internal temporary json data.
1. Added JSON formatter
2. Upload the 'official' `coverage.json` to sonarcloud instead of the private `.resultset.json`
According to https://jira.sonarsource.com/browse/SONARSLANG-477 this should now be working :crossed_fingers:
=> Include JSON code coverage report and use for sonarcloud

Dockerfile
https://trello.com/c/c4lViBfR
Builds are broken because they depend upon a no longer available mimemagic gem, and the docker cache has expired.
1. Use the last working build as a cache source as a stop gap fix
=> Build from working cached build

Dockerfile
Creating the app sha file will result in a new file on every build. Since this
is before the Gem installation, it will result in Gems being reinstalled on
every build irrespective of whether the cache could supply the Gems.
Instead move it to the final step since its guarenteed to be different for every
build.
=> Avoid reinstalling gems on every build

app/views/pages/home.html.erb
https://trello.com/c/UBw5S7wu/586-review-content-on-welcome-page-for-tta-service
We have >30% drop out on the startpage of our GOV.UK styled Get an Adviser service. This may be due to the volume of copy we present, and its user friendliness.
Updated copy:
- better value exchange of what the Get an Adviser service offers
- clearer copy on requirements and eligibility
Is this a sufficient improvement on previous copy? If so, deploy and analyse drop off rates.
=> Update startpage content

.github/workflows/deploy.yml
Terraform is getting a little old and dependancies may start to fail. 14.9 is working and safe, so use that in delivery from now
=> Upgrade Terraform

yarn.lock
https://trello.com/c/AhoaZMmA
We should try to minimize the warnings we are getting from the CVE scanner. A lot are coming from our NPM dependencies
1. Upgrade all NPM dependencies
=> Upgrade all npm dependencies

app/views/teacher_training_adviser/not_available.html.erb, app/views/teacher_training_adviser/steps/_already_signed_up.html.erb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
https://trello.com/c/H20rftsn/1428-change-phone-number-on-site-to-0800-389-2500
We are updating the phone number back to the old number, as we take over the new domain.
Any phone number reference from 2501 -> 2500.
Has every instance been corrected? I used find and then replaced individually, so I imagine so.
=> Updated phone number

public/robots.txt
We only want to allow the root page of the TTA service to be indexed by search engines.
=> Only allow root page to be indexed

app/controllers/robots_controller.rb, config/environments/development.rb, config/environments/preprod.rb, config/environments/production.rb, config/environments/rolling.rb, config/environments/userresearch.rb, config/routes.rb, public/robots.txt, spec/requests/beta_redirect_spec.rb, spec/requests/robots_spec.rb
- Redirect beta domain to new prod domain
We now have a non-beta production domain; all requests to the beta domain should be redirected.
- Serve robots.txt from Rails
We want to serve the robots.txt file from Rails so that we can intercept calls on the beta- domain and redirect them.
=> Redirect beta domain to new prod domain

terraform/paas/application.tf, terraform/paas/data.tf, terraform/paas/production.env.tfvars, terraform/paas/provider.tf, terraform/paas/services.tf, terraform/paas/statuscake.tf, terraform/paas/test.env.tfvars, terraform/paas/ur.env.tfvars, terraform/paas/variables.tf
Allow the TTA service access to the Postgres DB
- Renamed the variable for linking the redis service to be more generic and made it a list
- Terraform now collects data from the list
- Terraform now attaches the list of service_ids to the application
This does not impact the application
The latest version of `terraform fmt` has got fussy and made a few format changes.
=> Add Postgres To TTA

app/controllers/concerns/circuit_breaker.rb, spec/requests/circuit_breaker_spec.rb
https://trello.com/c/Z9YPUZ5Q
The API client will raise a CircuitBrokenError if there are repeated API failures. See PR [here](https://github.com/DFE-Digital/get-into-teaching-api-ruby-client/pull/37)
When this happens, the error should be logged to Sentry
- Log to Sentry when CircuitBrokenError is raised in the client Gem
=> Log to Sentry when CircuitBrokenError is thrown in client Gem

Gemfile, Gemfile.lock, app/controllers/teacher_training_adviser/feedbacks_controller.rb, app/views/teacher_training_adviser/feedbacks/new.html.erb, config/initializers/invisible_captcha.rb, spec/features/feedback_spec.rb
[Trello-1406](https://trello.com/c/HrLZDKvi/1406-create-new-feedback-form-for-tta-service)
At the moment a bot could easily submit the feedback form; we want to prevent that so that we only get authentic submissions from candidates.
Add `invisible_captcha` gem, which puts three forms of protection onto the page:
- A hidden honey pot field (if filled in the submission is rejected).
- A 'spinner' field (if modified the submission is rejected).
- A minimum submission time (too-fast submissions are rejected).
If a submission is rejected we render a HEAD 200 response, which should be enough to make the bot think it was successful/hopefully it then moves on.
- Add invisible captcha protection to feedback form
You can manually trigger the bot protection by filling in the honey pot field before …
=> Add invisible captcha protection to feedback form

app/models/teacher_training_adviser/feedback_search.rb, lib/teacher_training_adviser/feedback_exporter.rb, spec/features/feedback_spec.rb, spec/lib/teacher_training_adviser/feedback_exporter_spec.rb, spec/models/teacher_training_adviser/feedback_search_spec.rb, spec/requests/basic_auth_spec.rb, spec/requests/feedback_spec.rb, spec/support/spec_helpers/basic_auth.rb
[Trello-1406](https://trello.com/c/HrLZDKvi/1406-create-new-feedback-form-for-tta-service)
A CSV cell that begins with `+`, `-`, `@` or `=` could contain malicious formula. To prevent CSV injection these cells must be prefixed with a `'`.
I noticed that in the review environment a validation error was occurring when the "Created on or before" date defaults to today; I think this is because the current time is being compared in the validation conditional, even though I couldn't replicate it locally. Updating to be `end_of_day` to see if that resolves it.
- Escape CSV injection payloads
- Tweak created_on_or_before validation to be looser
- Prevent flakiness in environment tests
We're seeing flakiness around the tests against `BasicAuth` due to the credentials being memoized in a class …
=> Minor follow up tweaks to CSV exporting

app/controllers/teacher_training_adviser/feedbacks_controller.rb, spec/requests/feedback_spec.rb
We are correctly prompting for the basic auth now, but incorrectly showing a forbidden page on rolling/pre-prod for actions a regular user should be able to do.
Take into account the `action_name` when restricting access in addition to determining if we should prompt for authentication.
=> Only restrict access on certain feedback actions

.env.test, config/initializers/01_vcap.rb, config/initializers/01_vcap_services.rb, lib/prometheus/metrics.rb, spec/lib/metrics_spec.rb
[Trello-1404](https://trello.com/c/9UOVcX50/1404-improve-metrics-output-to-prometheus)
We want to be able to differentiate all metrics against preset labels:
- Application
- Organization
- Space
This will enable us to tailor alerts more suitably to the specific environment running.
- Add preset labels to all custom metrics
=> Add preset labels to all custom metrics

config/environments/development.rb, config/environments/production.rb, config/initializers/get_into_teaching_api_client.rb, spec/requests/instrumentation_spec.rb
The API client library is being updated to support cache invalidation under certain scenarios (for example, posting a new teaching event needs to clear the event search cache).
As invalidating specific response caches would be reasonably tricky (the caching is performed by a separate middleware) the API client instead blows away its entire cache store (the cache is short-lived and cheap). It is no longer safe to use `Rails.cache` for the API client and instead we need to isolate the cache, so we don't invalidate anything apart from cached HTTP responses.
The TTA service doesn't support any of the endpoints that invalidate cache at the moment, but we should still isolate the cache to protect against future changes.
- Isolate Api client HTTP cache store
Use a new in-memory cache for …
=> Isolate API client HTTP cache store

app/models/wizard/issue_verification_code.rb, spec/support/shared_examples/wizard_support.rb
If the API responds with a non-404 error on the match back endpoint then we are potentially creating a duplicate Candidate record in the CRM (as we have been unable to verify against an existing Candidate record).
Add logging so that we can easily search for these occurrences.
Add logging so that we can easily identify requests for access tokens by transaction (TTA in this case).
=> Log when a duplicate Candidate is potentially being created

config/initializers/instrumentation.rb, spec/requests/instrumentation_spec.rb
For some reason the metric label for `tta_feedback_visit_total` is always coming back as `true` and the `false` value is never present, even when its definitely been selected by a user.
I'm clutching at straws here, but trying different true/false values in case `false` is reserved/special for some reason.
=> Fix feedback metric label not registering correctly

app/controllers/application_controller.rb, app/controllers/teacher_training_adviser/feedbacks_controller.rb, lib/basic_auth.rb, spec/lib/basic_auth_spec.rb
Shift the site-wide auth determination into the `BasicAuth` module and clean up the `FeedbacksController` with call to
`super`.
=> Minor tidy up of basic auth logic

.github/common_environment.yml, .github/workflows/build.yml, .github/workflows/deploy.yml, terraform/paas/application.tf, terraform/paas/data.tf
https://trello.com/c/F01QXCqc/1526-migrate-to-github-container-registry
Docker Hub have limited the amount of users and the amount of pulls that we can do, It is also another service we need to manage, when we can now use GHCR which keeps the docker image with the source and does not have the restrictions of docker hub.
When building or deploying docker images store and retrieve them from GitHub Container Repository.
No change to application
=> Migrate to GHCR

.github/workflows/deploy.yml
On deploy retrieve the Logit.io API key so we can log a deployment event, thus enabling some sort of chart in Grafana
=> Retrieve Logit Secret

Gemfile, Gemfile.lock, config/environments/production.rb, config/puma.rb
[Trello-1573](https://trello.com/c/futEUxSe/1573-trim-some-of-the-logging-fat)
We want to log in a compact JSON format, as we already do in the GiT app.
Add the SemanticLogger gem and configure so it will work well with logit.io.
Log at the `info` level in production instead of `debug`.
- Switch to SemanticLogger
=> Switch to SemanticLogger in Production

.env.production, config/initializers/rack_attack.rb
[Trello-1568](https://trello.com/c/2fmvfC4A/1568-look-to-increasing-fail2ban-time-for-a-longer-period)
- Update Fail2Ban length to 5 minutes
- Send Fail2Ban violations to the logs
We are receiving a fair amount of exceptions due to Fail2Ban being triggered; its not an exceptional case and shouldn't be treated as an error, so sending these to the logs and setting up a Grafana dashboard to monitor them feels more appropriate.
=> Update Fail2Ban settings

app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
TPUK have extending their contact hours to 530pm (from 5pm), amending references to it.
Have I caught all references (that aren't quotas/time slots for callbacks)?
=> Amending opening hours for phone line

Gemfile.lock, app/models/teacher_training_adviser/steps/overseas_telephone.rb, app/models/teacher_training_adviser/steps/overseas_time_zone.rb, app/models/teacher_training_adviser/steps/uk_callback.rb, app/models/teacher_training_adviser/steps/uk_telephone.rb, app/views/teacher_training_adviser/steps/_overseas_telephone.html.erb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/_uk_callback.html.erb, app/views/teacher_training_adviser/steps/_uk_telephone.html.erb, config/initializers/filter_parameter_logging.rb, config/locales/en.yml, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/overseas_telephone_spec.rb, spec/models/teacher_training_adviser/steps/overseas_time_zone_spec.rb, spec/models/teacher_training_adviser/steps/review_answers_spec.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb, spec/models/teacher_training_adviser/steps/uk_telephone_spec.rb
The API currently supports both field names, but telephone is being deprecated in favour of address_telephone.
=> Rename telephone to address_telephone

app/views/pages/cookies.html.erb, app/views/pages/home.html.erb
As 'teacher training advisers' isn't a service name it should be lower case. This change brings this application in line with the app and content repos.
=> Lowercase 'teacher training advisers'

app/models/teacher_training_adviser/steps/identity.rb, app/validators/email_format_validator.rb, config/locales/en.yml, spec/models/teacher_training_adviser/steps/identity_spec.rb, spec/validators/email_format_validator_spec.rb
The built-in URI email regex appears to allow emails without fully qualified domains, such as `some@thing`. We use a custom email format validator in the GiT app that is more suitable for our use-case, so this is a lift and shift of that validator into the TTA codebase.
=> Improve email format validation

config/locales/en.yml
help text talks about 'the return to teaching route' - this is super confusing as there's no obvious part of the form (from a user's perspective) that is the 'return to teaching route'
=> help text confusing

app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb
=> use 'and' rather than an en rule or hyphen and reduce sentence length

Gemfile, Gemfile.lock, app/models/teacher_training_adviser/steps/overseas_telephone.rb, app/models/teacher_training_adviser/steps/overseas_time_zone.rb, app/validators/telephone_validator.rb, app/views/teacher_training_adviser/steps/_overseas_telephone.html.erb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, config/locales/en.yml, spec/models/teacher_training_adviser/steps/overseas_telephone_spec.rb, spec/models/teacher_training_adviser/steps/overseas_time_zone_spec.rb, spec/validators/telephone_validator_spec.rb
[Trello-1597](https://trello.com/c/WCPR0FxQ/1597-overseas-number-validation-sanitisation)
When a candidate is overseas we need to ensure that their telephone number will be in a format that the TPUK dialling system supports. On the client-side this means the number needs to be prefixed by the country dial-in code (e.g. 44). The API will then sanitise the number further to remove non-numerical values, white space and a proceeding `+`.
- Update international telephone validation
=> Update international telephone validation

app/models/teacher_training_adviser/steps/overseas_country.rb, app/models/teacher_training_adviser/steps/overseas_telephone.rb, app/models/teacher_training_adviser/steps/overseas_time_zone.rb, app/views/teacher_training_adviser/steps/_overseas_telephone.html.erb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/overseas_country_spec.rb, spec/models/teacher_training_adviser/steps/overseas_telephone_spec.rb, spec/models/teacher_training_adviser/steps/overseas_time_zone_spec.rb, spec/support/shared_examples/address_telephone_value.rb
[Trello-1618](https://trello.com/c/bOmVyBvV/1618-pre-fill-country-dial-in-code-from-country-selection)
A candidate selects their country of residence before entering their telephone number; we can lookup the dial-in code for their selected country and pre-fill the telephone input field to make entering their number easier/less error prone.
- Prefill telephone dial-in code from country selection
=> Prefill country dial in code

app/models/teacher_training_adviser/steps/overseas_country.rb, spec/models/teacher_training_adviser/steps/overseas_country_spec.rb
If the user gets to the step asking them for their overseas telephone number before they have specified their country of residence we get an exception due to the `country_name` being `nil`. This should only be possible if someone skips ahead by manually entering the URL of a future step or if their session expires part way through, perhaps.
Default to no country-code being pre-filled if the country of residence is not yet known.
=> Fix bug on pre-filling country dial-in code

app/models/concerns/callback_booking_quotas.rb, spec/features/sign_up_spec.rb, spec/support/shared_examples/callback_booking_quotas.rb
[Trello-1626](https://trello.com/c/SRdITVG8/1626-international-dialing-outstanding-issues)
We were previously limiting the earliest booking slots to the following day, however we now want to allow candidates to book a slot on the current day, but omit any in the next hour to give TPUK enough time to receive and process the
booking.
- Show booking slots as available unless they are in the next hour
=> Show booking slots as available unless they are in the next hour

app/views/shared/_cookie_banner.html.erb
[Trello-1623](https://trello.com/c/6yvBReQt/1623-investigate-the-impacts-of-privacy-software-on-the-usability-of-the-site)
It appears that AdBlockers in general allow our cookie modal to appear, however they hide the "Accept all cookies" button (seemingly targetting the `id` because it includes `cookie`).
A workaround is to rename the `id` to something else - I've left a note in the code to prevent this from being changed back in the future.
- Rename accept cookies button id to bypass ad-blockers
The only way I was able to replicate this bug was to install uBlock and enable all of the 'annoyances' under filters:
=> Rename accept cookies button id to bypass ad-blockers

app/models/teacher_training_adviser/steps/have_a_degree.rb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/_uk_callback.html.erb, config/locales/en.yml, spec/features/sign_up_spec.rb
https://trello.com/c/SS8BgX7s/1611-get-an-adviser-copy-suggestions-to-review
We've had a variety of requests from Candidate Experience around how we could improve our Get an Adviser flow. This comes off the back of feedback that many users are going down the 'returners' route when they should be going down the standard, teacher training adviser, route. Some of these copy changes aim to help rectify that issue, which is having a knock on effect on TPUK.
=> Various TTA changes based on feedback

package.json, yarn.lock
Upgrade Jest to 27.0.4 - this PR is needed in addition to the original dependabot one because to make the tests run we need to set the [testEnvironment](https://jestjs.io/docs/configuration#testenvironment-string) to `jsdom`.
Fixes #713
=> Upgrade Jest to 27.0.4

config/environments/development.rb, config/environments/production.rb, lib/basic_auth.rb, spec/lib/basic_auth_spec.rb, spec/requests/basic_auth_spec.rb, spec/requests/feedback_spec.rb, terraform/paas/application.tf, terraform/paas/production.env.tfvars, terraform/paas/ur.env.tfvars, terraform/paas/variables.tf
- Use env variable to control basic auth on/off
Instead of controlling explicitly by the named environment we want to be able to toggle basic auth on/off with an env variable more easily.
- Add BASIC_AUTH env to infrastructure
Enabled by default, disabled in production and UR environments.
=> Use env variable to control basic auth on/off

docs/runbooks/pipelines/build_fails_at_release.md
[Moving Run Books ](https://trello.com/c/0GUCpmZv/1502-move-runbooks-from-confluence-to-github-pages)
Adding Procedures to assist with manually resolving common problems.
=> document how to fix failure

app/controllers/teacher_training_adviser/steps_controller.rb, spec/features/sign_up_spec.rb
We were only setting the users time zone on `show` actions, but the view will be rendered on an `update` action that fails validation so we need to ensure the correct time zone is applied in that scenario as well.
Add test to check the time zone offset works for both `show` and `update` actions.
=> Correct time zone on update action

spec/support/shared_examples/rate_limiting_support.rb
[Trello-1682](https://trello.com/c/G58c4oz0/1682-investigate-flakey-rate-limit-specs-in-the-app-tta)
These appear to fail completely at random - an rspec bisect results in a test sequence that subsequently passes.
My theory is that `Rack::Attack` works on time boundaries rather than a rolling window; so I expect if the test runs across a minute boundary and the period is also 1 minute then it will fail because it expects a 429 and gets a 200. To avoid this I am freezing time at the start of the test. I've also added more padding to the travel time to check the rate limit doesn't apply after the period has elapsed (10 seconds up from 1 second) incase there's something iffy going on there as well.
- (Hopefully) fix flakey rate limit specs
=> (Hopefully) fix flakey rate limit specs

config/application.rb
We don't need to use the `DataFileStore` as we only run a single Puma process.
=> Use default Prometheus client data store

spec/helpers/answer_helper_spec.rb
[Trello-1715](https://trello.com/c/y9CGlnNR/1715-investigate-flakey-tta-spec)
The `AnswerHelper` spec was modifying `Time.zone` directly; this effected the contract specs on occasion as the `StepsController` also sets `Time.zone` to the users locale. Instead, we should stub `Time.zone` so that it can be changed
in the scope of the test being ran.
- Fix flakey spec caused by Time.zone
=> Fix flakey spec caused by Time.zone

config/locales/en.yml
We're seeing many people click 2021 when actually they want to apply in 2022. Adding some suggested help text to see if this helps.
This is the first of 2 changes. The other (changing drop down options) will be done in a separate PR.
=> Add helptext for Year of Start

app/models/teacher_training_adviser/steps/start_teacher_training.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb
[Trello-1725](https://trello.com/c/TgiZwDpw/1725-update-copy-for-tta-start-teacher-training-year-options)
We want to update the labels fo the teacher training years, which come back from the CRM as '2021', 2022', etc. Instead, if the year is the current year we want to show the format:
```
<year> - start your training this September
```
We only show the current year up until September. If the year is a future year we want to use the format:
```
<year> - start your training in September <year>
```
- Update labels for teacher training years
https://review-teacher-training-adviser-760.london.cloudapps.digital/teacher_training_adviser/sign_up/start_teacher_training
=> Update labels for teacher training years

app/models/teacher_training_adviser/feedback_search.rb
[Trello-1777](https://trello.com/c/4ZcdcnJs/1777-fix-bug-on-future-date-selection-of-feedback-exporter)
The validation for the FeedbackSearch `on_or_before` attribute was comparing a `Date` to a `Time` with some odd results. Ensuring we `to_date` the `Time` first corrects the behaviour.
- Fix on_or_before validation
=> Fix on_or_before validation

Gemfile.lock, app/models/teacher_training_adviser/steps/already_signed_up.rb, app/models/wizard/base.rb, spec/contracts/data/teacher_training_adviser/candidates.json, spec/models/teacher_training_adviser/steps/already_signed_up_spec.rb, spec/models/wizard/base_spec.rb
> :warning: **Do not merge until CRM team have tested on the review instance**
[Trello-1698](https://trello.com/c/yG3hzAuh/1698-development-unblock-get-an-adviser-applicants-who-have-previously-had-an-adviser)
Previously we were using the `already_subscribed_to_teacher_training_adviser` field to determine if we prevent the user from continuing with their sign up. Instead, we want to use the `can_subscribe_to_teacher_training_adviser` field which will allow some candidates that have already subscribed to re-subscribe (depending on their adviser status as determined by the
API).
- Bump API Client version
- Allow some candidates to re-sign up for a TTA
=> Allow some candidates to re-subscribe for a TTA

app/models/teacher_training_adviser/steps/start_teacher_training.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb
The marketing team have asked for us to display the next teacher training year on the 7th September instead of the 18th.
=> Show next year on 7th September instead of 18th

app/views/teacher_training_adviser/steps/completed.html.erb
Removing messaging that encouraged candidates to act speedily to make sure they could get their application in before the September deadline.
https://trello.com/c/vViTOgMo/1904-update-years-and-confirmation-page-on-get-an-adviser-form
=> Removing year end messaging

Gemfile.lock, app/models/teacher_training_adviser/steps/identity.rb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_identity.html.erb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/identity_spec.rb
[Trello-2498](https://trello.com/c/KKq8jc3M/2498-on-campus-channel-attribution-for-tta-sign-up)
The events team are pushing TTA sign ups at on-campus events and want to be able to attribute a successful sign up to a particular event. The API now accepts a `channe_id` in the TTA sign up request model, so this PR updates the TTA root URL to forward on a `channel` attribute, that will be used for the `channel_id` when signing up. It is persisted as part of the first (identity) step.
To sign up the URL format is:
```
/?channel=<channel_id>
```
- Support custom channel in TTA sign up
=> Support custom channel in TTA sign up

.env.production, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/environments/preprod.rb, config/environments/production.rb, config/environments/rolling.rb, config/environments/userresearch.rb, spec/helpers/application_helper_spec.rb, spec/requests/gtm_spec.rb
> :warning: Update GA ID in GTM to prod before merging this
Switch to using the new GTM container in production. Switches non-prod environments back to the legacy tracking method so we don't pollute the prod GA account with traffic from non-prod environments.
=> Enable new GTM container in production

app/webpacker/javascript/gtm.js, spec/javascript/gtm_spec.js
This is a lift and shift of the changes in https://github.com/DFE-Digital/get-into-teaching-app/pull/2108 (as the GTM container is shared by both services).
=> Prevent loss of Google Ads tracking parameters

.env.test, lib/prometheus/metrics.rb, spec/lib/prometheus/metrics_spec.rb
The metrics are not correctly aggregating due to multiple instances sending the same metric/labels. We need another label to differentiate between metrics so that Prometheus correctly aggregates them.
A change made to Prometheus also requires this label or it ends up stuck in a loop and forever incrementing the counter.
=> Add app_instance label to all metrics

Dockerfile
Address vulnerability in expat/expat, see: https://security.snyk.io/vuln/SNYK-ALPINE314-EXPAT-2342148
=> Bump docker image to alpine3.15

Dockerfile, Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, app/webpacker/javascript/gtm.js, app/webpacker/packs/application.js, app/webpacker/styles/application.scss, package.json, spec/javascript/gtm_spec.js, yarn.lock
[Trello-2586](https://trello.com/c/t010C4f7/2586-re-deploy-turbo-upgrade-once-we-have-migrated-to-the-new-gtm-container)
Turbolinks is deprecated in favour of Turbo, which is part of Hotwire. It is more robust than Turbolinks and fixes many of the... quirks... that are in Turnbolinks.
- Updade to Turbo
Pull in Turbo instead of Turbolinks.
Update references to `turbolinks` with `turbo`.
=> Upgrade to Turbo

config.ru
[Trello-2896](https://trello.com/c/dHyE1XU0/2896-rework-labels-sent-with-prometheus-metrics-in-the-app-tta-service)
The middleware collects HTTP request duration/count, but we have our own custom metrics for this and don't actually reference them in any of our dashboards and they don't have the standard set of app/instance/etc labels.
- Remove default Prometheus Collector middleware
=> Remove default Prometheus Collector middleware

app/models/teacher_training_adviser/steps/have_a_degree.rb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_no_degree.html.erb, app/views/teacher_training_adviser/steps/_subject_not_found.html.erb, config/locales/en.yml, spec/contracts/sign_up_spec.rb, spec/features/sign_up_spec.rb
[Trello-1739](https://trello.com/c/T4TyDmCh/1739-get-an-adviser-content-changes)
Update the copy on the home page, subject not found, returning teacher and have a degree and no degree steps.
- Copy updates for various steps
| Home  | Returning Teacher  | No Degree | Subject Not Found | Have a Degree |
|---|---|---|---|---|
|   <img width="1199" alt="Screenshot 2022-01-20 at 11 31 34" src="https://user-images.githubusercontent.com/29867726/150330820-1dae315a-3b4d-4728-b86f-157b3c6e04b1.png">  |   <img width="1199" alt="Screenshot 2022-01-20 at 11 31 41" src="https://user-images.githubusercontent.com/29867726/150330841-0c829207-feff-4408-8b7d-eee2c2963b18.png">  |   <img width="1199" alt="Screenshot 2022-01-20 at 11 31 56" src="https://user-images.githubusercontent.com/29867726/150330879-845 …
=> Copy updates for various steps

Dockerfile, Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, app/webpacker/javascript/gtm.js, app/webpacker/packs/application.js, app/webpacker/styles/application.scss, package.json, spec/javascript/gtm_spec.js, yarn.lock
Reverts DFE-Digital/get-teacher-training-adviser-service#908
Turbo was having a negative knock-on effect to our PPC campaigns on the GiT website; we're not sure why, but we should revert to Turbolinks here in case it causes the same issues on the TTA service.
=> Revert "Upgrade to Turbo"

app/helpers/form_helper.rb, app/views/teacher_training_adviser/steps/_authenticate.html.erb, app/views/teacher_training_adviser/steps/_form.html.erb, app/views/wizard/steps/_authenticate.html.erb, config/locales/en.yml, spec/features/sign_up_spec.rb, spec/helpers/form_helper_spec.rb, spec/support/spec_helpers/contract_helper.rb
[Trello-2902](https://trello.com/c/KGD3HyIm/2902-improve-content-of-verification-code-step-in-the-get-an-adviser-funnel)
This step doesn't perform all that well and we see roughly 1/5 users drop off/don't successfully enter their verification code and progress to the next step.
In an effort to tackle this we are making the copy clearer/reworking the layout of the step (this will bring it inline with the GiT website transactions).
- Rework the enter verification code step
The Cypress tests will need to be updated when this is shipped.
=> Rework the enter verification code step

config/locales/en.yml
Changing hint text for question 'are you qualified to teach?' from:
> Select 'yes' if you are a returning teacher and have qualified teacher status (QTS), or have an overseas teaching qualification.
to:
> Only select 'yes' if you have qualified teacher status (QTS).
https://trello.com/c/4bSp8yzy/2943-get-an-adviser-question-change
=> Updating QTS hint text

.github/workflows/build.yml
I missed this from the original PR; the deployment run failed as postgres isn't available.
=> Add postgres service to QA test step

.github/workflows/build.yml, Dockerfile, Gemfile, Gemfile.lock, spec/capybara_driver_helper.rb, spec/rails_helper.rb, terraform/paas/application.tf
The TTA service hadn't been setup with selenium so the tests were failing. The docker image is now also bigger as it includes chromium, so I've had to up the disk quota.
The chromium package isn't compatible with a previous security fix - I've removed the workaround for now; it may still get flagged by snky, in which case I'll need to find another way around it.
=> Fix integration tests not running

Dockerfile
There are vulnerabilities in the versions of these packages within the alpine-3.15 image; manually upgrading them to placate snyk.
=> Upgrade libxslt and libxm2

spec/integration/sign_up_spec.rb, spec/support/spec_helpers/contract_helper.rb
The existing sign up integration test is currently failing because the candidate is not in the required state to prevent them re-signing up.
Instead, change the test to do a full sign up using an existing candidate record, which is arguably more thorough/useful anyway.
=> Run through full sign up as existing candidate

app/models/teacher_training_adviser/steps/identity.rb, app/models/teacher_training_adviser/wizard.rb, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/_identity.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb, config/locales/en.yml, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/identity_spec.rb
[Trello-3051](https://trello.com/c/oMCKU9xZ/3051-improve-error-message-when-channel-id-is-invalid)
Our on-campus events provide a `channel=` query string parameter (by way of a QR code/URL). If the channel is invalid we currently show an unhelpful error message.
Whilst it shouldn't be possible for users to encounter this scenario, if the QR code author makes a mistake it _could_ lead to
the user running into it. 
Handle the error more gracefully by clearing the channel and allowing the user to continue.
In addition to the `channel` we already record we want to allow BAM to send a `sub_channel` in the query string so that they can better attribute sign ups.
- Handle when invalid channel id is specified
Also fixes a bug whereby the channel ID was dropped if the user hits a validation error …
=> Handle when invalid channel id is specified

.github/workflows/destroy.yml
https://trello.com/c/GduNhcDq
Failure to delete dependabot related review apps: https://github.com/DFE-Digital/get-teacher-training-adviser-service/runs/5867150170?check_suite_focus=true
The creation of review app for dependabot PRs is skipped. So we shouldn't try to delete the review app.
=> [557] Skip dependabot review app deletion

.env.userresearch, .rubocop.yml, Gemfile, config/database.yml, config/environments/userresearch.rb
[Trello-1660](https://trello.com/c/eRpJcktw/1660-migrate-all-secrets-from-rails-credentials-to-the-azure-keyvaults)
We currently store our secrets in a mixture of Rails credentials and Azure keyvaults; we want to store them all in the same place and Azure keyvaults is more secure, so we are migrating them to there.
- Remove userresearch environment
As far as I can tell the user research environment in Cloud Foundry just uses the `test` Azure keyvault, which sets `RAILS_ENV=preprod` so the `userresearch` environment is never actually used.
=> Remove userresearch environment

config/initializers/get_into_teaching_api_client.rb, config/initializers/sentry.rb, lib/basic_auth.rb, spec/support/vcr.rb
[Trello-1660](https://trello.com/c/eRpJcktw/1660-migrate-all-secrets-from-rails-credentials-to-the-azure-keyvaults)
We no longer use Rails credentials but some of the code will default to the Rails creds if an ENV var is not set; we no longer need to do that.
- Remove references to Rails credentials
=> Remove references to Rails credentials

.github/workflows/build.yml
Dependabot by default has readonly permissions, some steps in the workflow require write permissions.
This change sets workflow permissions for Actions and Dependabot.
Check that workflow is running as expected.
=> Add permissions to build and deploy workflow

.github/workflows/build.yml, .github/workflows/manual.yml
https://trello.com/c/JKv5aLRr
Maintaining a Github PAT is a maintenance burden
Replace with default Github actions token
Check the actions don't need a specific PAT
=> Remove service account token

app/helpers/application_helper.rb, app/views/teacher_training_adviser/steps/review_answers/_answer.html.erb, config/locales/en.yml, spec/helpers/application_helper_spec.rb
[Trello-3246](https://trello.com/c/4FF0yGO4/3246-dac-audit-non-descriptive-links-tta-funnel-review-answers)
[Trello-3247](https://trello.com/c/F8x4mWUn/3247-dac-audit-label-in-name-review-answers)
Currently the links to change your answer on the review answers page infer the visually-hidden text from the step name. This is not often a good experience for the user and results in phrases such as:
"Change identity" instead of "Change your email"
As multiple answers are part of the same step it also means the text is duplicated which can be confusing.
Instead, the visually-hidden text should relate to the specific answer being changed.
- Make change links on review answers page more accessible
As per the [GDS guidance](https://design-system.service.gov.uk/patterns/check-answers/)
=> Make change links on review answers page more accessible

app/views/layouts/application.html.erb, app/webpacker/controllers/cookie-acceptance_controller.js
[Trello-3259](https://trello.com/c/FIlbKkHq/3259-dac-audit-skip-links)
Currently the skip to main content link appears below the cookie banner. This means its not the first thing you get to when you hit tab after the page loads and it also means the focus goes to the accept cookies button after selecting the skip to main content link (when it should go to the first focusable item in the main content).
Move the cookie banner to be below the skip to main content link so that it doesn't steel the initial focus. Update the cookie banner JS to stop the auto-focus onto the accept cookies button (I'm not sure why we were doing this in the first place).
- Fix skip to main content behaviour
=> Fix skip to main content behaviour

app/controllers/client_metrics_controller.rb, app/webpacker/controllers/cookie_preferences_controller.js, app/webpacker/javascript/cookie_preferences.js, config/initializers/instrumentation.rb, config/initializers/rack_attack.rb, config/routes.rb, lib/prometheus/metrics.rb, spec/javascript/controllers/cookie-acceptance_controller_spec.js, spec/javascript/controllers/cookie_preferences_controller_spec.js, spec/javascript/cookie_preferences_spec.js, spec/javascript/gtm_spec.js, spec/lib/prometheus/metrics_spec.rb, spec/requests/client_metrics_spec.rb, spec/requests/instrumentation_spec.rb
[Trello-3253](https://trello.com/c/8nYhdlGL/3253-enable-monitoring-of-cookie-opt-in-rate-on-the-tta-funnel)
We want to be able to track some metrics that trigger from the client-side. As all our metrics go via Prometheus we will need to send the information to Rails from the client in order to track it.
- Add ability to track client-side metrics
Add `ClientMetricsController` to accept incoming client metric information from Javascript.
Add `tta_client_cookie_consent_total` metric as the first client-side metric to track the opt-in success rate.
- Update interface to accept setting multiple categories
We want to be able to emit an event when cookies change; currently we use a `setCategory` method that is called multiple times, so the `CookiePreference` class doesn't know when all the …
=> Track cookie opt-in rates

Dockerfile, app/views/cookie_preferences/show.html.erb, app/views/errors/forbidden.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/errors/too_many_requests.html.erb, app/views/errors/unprocessable_entity.html.erb, app/views/layouts/application.html.erb, app/views/pages/accessibility.html.erb, app/views/pages/cookies.html.erb, app/views/pages/home.html.erb, app/views/pages/privacy_policy.html.erb, app/views/pages/session_expired.html.erb, app/views/teacher_training_adviser/feedbacks/index.html.erb, app/views/teacher_training_adviser/feedbacks/new.html.erb, app/views/teacher_training_adviser/feedbacks/thank_you.erb, app/views/teacher_training_adviser/steps/_form.html.erb, app/views/teacher_training_adviser/steps/_subject_not_found.html.erb
[Trello-3257](https://trello.com/c/twvsWl1m/3257-dac-audit-no-main-landmark)
The completed page did not contain a main landmark and so the skip to main content link was not working.
Update application layout to include the main landmark and add a new `yield` so that we can insert back links above it on the form steps.
- Ensure all pages have a main landmark
- Patch freetype vulnerability
=> Ensure all pages have a main landmark

lib/cloud_front_ip_filter.rb, spec/lib/cloud_front_ip_filter_spec.rb
If an invalid IP address makes it into the CloudFrontIpFilter it raises an IPAddr::InvalidAddressError to Sentry. These appear to originate from bots/non-user traffic but cause noise in Sentry, so handling it gracefully to silence the errors.
=> Handle invalid IP address gracefully

Gemfile, Gemfile.lock, package.json, yarn.lock
- Bump govuk-frontend from 4.0.1 to 4.1.0
- Bump nokogiri from 1.13.4 to 1.13.6
- Bump sentry-ruby from 5.3.0 to 5.3.1
- Bump capybara from 3.36.0 to 3.37.1
- Bump jest-environment-jsdom from 28.0.2 to 28.1.0
- Bump @rails/ujs from 7.0.2 to 7.0.3
- Bump rack-attack from 6.6.0 to 6.6.1
Closes #1028 #1025 #1018 #1017 #1015 #1014 #1006
=> Various dependency updates

config/initializers/secure_headers.rb
We are seeing a couple of CSP errors; Google appears to be using a new hostname and Twitter wants to load an image.
=> Update CSP directives

Gemfile.lock, app/models/teacher_training_adviser/steps/review_answers.rb, app/models/teacher_training_adviser/steps/uk_or_overseas.rb, app/models/teacher_training_adviser/wizard.rb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/review_answers_spec.rb, spec/models/teacher_training_adviser/steps/uk_or_overseas_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb
[Trello-3250](https://trello.com/c/lAuxvW5N/3250-dac-audit-gov-check-answers)
At the moment the candidate will have to go through the remainder of the wizard steps when they change an answer from the check answers page.
Instead, we want to jump them straight back to the check answers page if they have already completed the form.
- Skip steps the candidate has seen/submitted already
Pull in updated `dfe_wizard` gem which has this behaviour. Ensure the check answers step is always displayed to the user by overriding `#seen?`.
Default country to UK during data export instead of within the `uk_or_overseas` step; if we do it in the step it ends up setting the `country_id` and so the `overseas_country` step will be skipped if pre-filled when it shouldn't be (as its not optional).
[Corresponding …
=> Skip steps the candidate has seen/submitted already

config/environments/development.rb, config/locales/en.yml
[Trello-3416](https://trello.com/c/kx8angpq/3416-fix-time-zone-label-error-on-tta-funnel-check-answers-page)
There is a missing translation for the 'time zone' row on the check answers page, causing it to render as 'Title'.
- Add missing translation for overseas time zone
The translation was missing for the overseas time zone field, causing it to display 'Title' on the check answers page instead of 'Time zone'. It looks like it was placed under the wrong key in the translations file.
- Use in-memory store in development
If the Rails cache is disabled we were defaulting to a `null_store` for the cache; we later set the `session_store` to use the `cache_store`, however, so it was causing the session to immediately expire. Instead, we should use a `memory_store` in development (caching is …
=> Fix missing translation for time zone on check answers page

app/models/teacher_training_adviser/steps/start_teacher_training.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb
[Trello-3413](https://trello.com/c/4NbyCaGY/3413-update-training-years-in-the-tta-funnel?filter=member:rossoliver15)
We want to display an additional Initial Teacher Training (ITT) year on the 24th June (for 2022 this will be 2025). When we drop the current year on September 7th we _don't_ then want to show 2026, so the behaviour is as follows:
**Before 24th June:**
```
Not sure
Current year - start your training this September
Current year + 1
Current year + 2
```
**Between 24th June and 6th September:**
```
Not sure
Current year - start your training this September
Current year + 1
Current year + 2
Current year + 3
```
**After 6th September:**
```
Not sure
Next year
Next year + 1
Next year + 2
```
- Add additional ITT year on 24th June
This assumes the behaviour is going to be …
=> Add additional ITT year on 24th June

app/views/teacher_training_adviser/steps/completed.html.erb
https://trello.com/c/l5Zy697r/3466-update-backlink-to-funding-page-in-adviser-funnel
Adviser funnel still currently has a link to the old funding page. This needs changing to the new funding and support section.
=> updating funding link

.github/workflows/destroy.yml
https://trello.com/c/uFEpw9o2
Dependabot review apps are not deleted
Example: https://github.com/DFE-Digital/get-teacher-training-adviser-service/actions/runs/2823915112
We now create a review app for PRs raised by dependabot. The previous condition must be removed as it skipped it for dependabot.
Compare with GiT: https://github.com/DFE-Digital/get-into-teaching-app/blob/master/.github/workflows/destroy.yml
=> [656] Do not skip "Destroy review instance" for dependabot

app/models/teacher_training_adviser/steps/start_teacher_training.rb, spec/models/teacher_training_adviser/steps/start_teacher_training_spec.rb
[Trello-3531](https://trello.com/c/SRns0nx7/3531-confirm-when-tta-funnel-should-be-updated-to-remove-2022)
We want to update the copy around the first available year in the set of options depending on what the current date is. This is in an effort to clear up the reference to "this September" when the date is after the cutoff (7th September) and "this September" is actually "next September" until January 1st when it becomes "this September" again!
The logic is as follows.
**Current year is 2022**
1st January 2022 to 23rd June 2022:
```
Not sure
2022 - start your training this September
2023
2024
```
Between 24th June 2022 and 6th September 2022:
```
Not sure
2022 - start your training this September
2023
2024
2025
```
Between 7th September 2022 and 31st December 2022:
```
Not sure
2023 - …
```
=> Update copy on teacher training years options

spec/integration/sign_up_spec.rb
[Trello-3556](https://trello.com/c/LU7keESa/3556-fix-broken-tta-integration-tests)
The integration test for an existing candidate is being flakey; I'm not certain why yet but I think it may be to do with Capybara not resetting the session between tests consistently and it subsequently effects the existing candidate sign up journey.
Update the existing candidate test to simplify it; we really only care that the candidate gets a verification email and can proceed to the next step. The new candidate test will still ensure the submission to the API/CRM is working.
=> Fix flakey integration test

terraform/paas/production.env.tfvars
Remove the production StatusCake alert before we recreate it
using the new Terraform provider.
=> Remove alert before provider update

terraform/paas/production.env.tfvars, terraform/paas/provider.tf, terraform/paas/statuscake.tf, terraform/paas/variables.tf
Update the StatusCake provider to ensure it is not using a preview
version.
=> Update Terraform StatusCake provider to 2.0.3

.github/workflows/actions/deploy/action.yml, .github/workflows/destroy.yml, .tool-versions, terraform/paas/.gitignore, terraform/paas/.terraform.lock.hcl, terraform/paas/provider.tf
Ensure the Terraform version contains the latest fixes and supports Apple processors
- Update Terraform version to 1.2.8
- Successfully deployed to review app with 0.14.9 then once upgraded to 1.2.8
=> Upgrade Terraform to version 1.2.8

spec/features/sign_up_spec.rb
As we are now after 7th September the 2022 ITT year is excluded from the list of available years. Freezing the date to be earlier fixes it.
=> Fix flakey sign up specs

app/views/layouts/_footer.html.erb, spec/requests/gtm_spec.rb
[Trello-3680](https://trello.com/c/ZIH9FAhh/3680-add-contact-details-to-footer-of-tta-funnel)
We don't have an obvious/easy way for candidates to get in touch if they are having difficulties with the adviser service; we should display clear contact details on every page.
- Add get help section to footer
Add a new section to the footer with contact details.
=> Add get help section to footer

.github/dependabot.yml
We're finding the weekly interval too frequent and the number of PRs dependabot raises is a pain to keep on top of - monthly should work out better for us.
=> Change dependabot to monthly interval

config/initializers/secure_headers.rb
I'm not sure why these have started suddenly flagging as violations (the pixels have been enabled for months!).
Whitelist google ad services, reddit, hotjar and our GTM server-side container.
I plan on doing a clean up of the CSP directives in the future to get them more inline with those in the app and just generally tidied, but this fixes the immediate issues.
=> Update CSP to whitelist domains

Dockerfile, app/helpers/text_format_helper.rb, spec/helpers/text_format_helper_spec.rb
Our HTML whitelisting was too strict and stripping out headings/jump links. I'm updating it to match the same method on the Get into Teaching website so that its consistent.
=> Fix Privacy Policy formatting

config/initializers/secure_headers.rb
We need the HotJar domain in the `frame_src` directive as we see a violation in production just now.
=> Fix Hotjar CSP error

.env.test, Gemfile, Gemfile.lock, app/models/healthcheck.rb, app/webpacker/controllers/cookie-acceptance_controller.js, app/webpacker/controllers/cookie_preferences_controller.js, config/initializers/redis.rb, package.json, spec/javascript/controllers/cookie-acceptance_controller_spec.js, spec/javascript/controllers/cookie_preferences_controller_spec.js, spec/models/healthcheck_spec.rb, yarn.lock
[Trello-3808](https://trello.com/c/xYgwOwq5/3808-fix-csp-errors-on-tta-service)
The TTA service has various dependencies with major version bumps that we need to update and require a bit of refactoring for compatibility. 
- Upgrade to Stimulus v3
Upgrade to the latest version of Stimulus.
- Upgrade Redis to v5
Using a single connection to Redis is now discouraged because it can lead to blocking. The recommended fix is to enable connection pooling.
Wrap the existing connection using the connection_pool gem.
- Update dfe-analytics gem
Update to the latest version of `dfe-analytics`. There is an issue whereby the latest gem calls `eager_load!` which causes Rails to evaluate the `inclusion` validation block in `WhatDegreeClass` and make an external request (which fails due to being …
=> Update various dependencies

Dockerfile
https://security.snyk.io/vuln/SNYK-ALPINE316-PIXMAN-3105084
Used fixed version of pixman `pixman=0.40.0-r4`
=> Update pixman to fix vulnerability CVE-2022-44638

.github/workflows/actions/deploy/action.yml, .github/workflows/destroy.yml
https://trello.com/c/3s3iC7UV
The set-output command is being deprecated soon.
Resolution is to use $GITHUB_OUTPUT as per the workflow commands docs.
Confirm workflows complete:
=> Stop using set-output in check_sp workflow

app/views/shared/_cookie_banner.html.erb
[Trello-3847](https://trello.com/c/2CgyrH26/3847-dac-audit-non-descriptive-links-tta-cookies)
Our cookie acceptance message has a link with the text `hide` which is not very accessible for screen readers. Use `hide cookie message` instead.
- Update cookie hide link text
=> Update cookie hide link text

app/views/layouts/_footer.html.erb
https://trello.com/c/eUf7bdzY
Updated the phone number link text to improve the experience for screen readers and changed the opening hours to refer to bank holidays as we do elsewhere on the GiT website.
Added call to the link text for the phone number
Changed public holidays to bank holidays
=> Updated phone number link text and bank holidays

app/views/teacher_training_adviser/steps/completed.html.erb
https://trello.com/c/C8nLNnH0
As someone interested in teaching who has signed up for an adviser
I need to understand that there may be a delayed response over Christmas
So that my expectations are set correctly
Added a message to the completion page to explain there may be a delay in response times until January.
=> Added warning of slower response during holidays

app/models/application_record.rb, spec/requests/big_query_analytics_spec.rb, spec/requests/feedback_spec.rb
[Trello-4028](https://trello.com/c/oDECMFWN/4028-fix-deprecation-warnings-in-git-website-tta-service)
We no longer need to include `DfE::Analytics::Entities` explicitly; as of v1.4 it is included automatically.
- Fix dfe-analytics deprecation warning
=> Fix dfe-analytics deprecation warning

Dockerfile, app/views/pages/home.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb
https://trello.com/c/8tF71dr1
As an overseas qualified teacher
I need to understand whether I am eligible for an adviser
So that I can decide whether to complete the sign-up form
Added a notification banner for Non-UK teachers and strengthened the wording on the page
=> Stronger message QTS message for Non-UK teachers 

app/controllers/teacher_training_adviser/steps_controller.rb, app/models/teacher_training_adviser/steps/overseas_callback.rb, app/models/teacher_training_adviser/steps/overseas_time_zone.rb, app/models/teacher_training_adviser/steps/uk_callback.rb, app/models/teacher_training_adviser/wizard.rb, app/views/teacher_training_adviser/steps/_overseas_time_zone.html.erb, app/views/teacher_training_adviser/steps/_uk_callback.html.erb, app/views/teacher_training_adviser/steps/completed.html.erb, spec/features/sign_up_spec.rb, spec/models/teacher_training_adviser/steps/overseas_callback_spec.rb, spec/models/teacher_training_adviser/steps/overseas_time_zone_spec.rb, spec/models/teacher_training_adviser/steps/uk_callback_spec.rb, spec/models/teacher_training_adviser/wizard_spec.rb
[Trello-4062](https://trello.com/c/n5iRbaIL/4062-review-callback-quota-fallback-functionality-in-light-of-increased-demand)
Currently the API will provide a fallback list of available callback slots in the event the CRM returns none. Going forward the API will also return 0 if the CRM has none available.
We need to account for this in the front-end by asking the candidates to contact us instead of providing a mechanism for them to book a callback.
- Gracefully handle when there are no available callback slots
Update copy on steps that ask for a callback; on the overseas journey its actually two steps as we ask for their phone number/time zone before showing a list of callback slots (in their selected time zone). If the candidate is unable to book a callback we will not ask for their …
=> Gracefully handle when there are no available callback slots

app/views/layouts/_footer.html.erb
https://trello.com/c/5wC3G0jC/4124-remove-free-of-charge-from-adviser-funnel-footer-re-contact-centre-calls
The adviser funnel footer currently says the phone line is free of charge, but this isn't true for international users, so we should remove this.
=> Removing 'free of charge' from footer

.github/workflows/build.yml, .github/workflows/snyk.yml
[Trello-4152](https://trello.com/c/Xfa7qQ6L/4152-update-snyk-to-run-nightly)
We currently run Snyk on every build, which isn't necessary and blocks the pipeline when we have a vulnerability; going forward we will run it on a nightly schedule as we do in the GiT app.
=> Run Snyk nightly

package.json, yarn.lock
[Trello-4160](https://trello.com/c/tqXsfBuY/4160-fix-snyk-vulnerability)
There is a vulnerability in `nth-check`, which is a distant dependency of `webpacker` by way of `optimize-css-assets-webpack-plugin`. Manually upgrading this plugin to patch the security issue.
- Upgrade optimize-css-assets-webpack-plugin
We probably want to look at upgrading `webpacker` to one of the newer Rails 7 assets pipelines in the near future.
=> Upgrade optimize-css-assets-webpack-plugin

Dockerfile
[Trello-4260](https://trello.com/c/5ygbyXqA/4260-fix-snyk-vulnerabilities)
The version of openssl in the alpine docker image has vulnerabilities, see:
https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314624 
https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314641 
https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314643
=> Patch openssl vulerabilities

config/webpack/webpack.config.js, config/webpacker.yml, package.json, yarn.lock
[Trello-4299](https://trello.com/c/rzc4Pc09/4299-fix-shakapacker-not-reflecting-updated-css-js-in-development)
By default Shakapacker generates applicaton.js/css without any digest. This causes the browser to serve the cached version of the asset even after the
contents have changed.
- Prevent caching of JS/CSS assets in development
Change webpack to always generate JS/CSS asset filenames with a digest.
Also update webpack overlay to only show errors as we have deprecation warnings in dependencies we can't do anything about.
=> Prevent caching of JS/CSS assets in development

Gemfile, Gemfile.lock, config/initializers/cors.rb
[Trello-4264](https://trello.com/c/IBdTsDhA/4264-investigate-404-landing-pages-for-adviser-service)
A CORS preflight request is a CORS request that checks to see if the CORS protocol is understood and a server is aware using specific methods and headers.
It is an OPTIONS request, using three HTTP request headers: Access-Control-Request-Method, Access-Control-Request-Headers, and the Origin header.
We currently respond to all OPTIONS requests with a 404; instead, we can include the `rack-cors` gem to correctly service these requests.
- Support CORS preflight requests
=> Support CORS preflight requests

config/initializers/instrumentation.rb, lib/prometheus/metrics.rb, spec/lib/prometheus/metrics_spec.rb, spec/requests/instrumentation_spec.rb
[Trello-4256](https://trello.com/c/JE8s3iFB/4256-look-to-see-if-we-can-remove-metrics-to-alleviate-the-load-on-prometheus)
We are overloading our InfluxDB instance due to the amount of metrics we are processing. We don't tend to look at the cache read metric and its likely one of the busier ones so removing it to alleviate some of the load.
- Remove cache read metric
=> Remove cache read metric

Dockerfile
See [https://security.snyk.io/vuln/SNYK-ALPINE316-NCURSES-5606597](https://security.snyk.io/vuln/SNYK-ALPINE316-NCURSES-5606597)
And Snyk Security Scan was failing in nightly builds:
=> Fix ncurse vulnerability

Gemfile, Gemfile.lock, package.json, spec/requests/big_query_analytics_spec.rb, spec/requests/invalid_authenticity_token_spec.rb, yarn.lock
Various dependency updates
Bump git_wizard from 1cfc90f to 590da16
Bump get_into_teaching_api_client_faraday from a7a90dc to d96278f 
Bump pg from 1.4.4 to 1.5.3
Bump govuk-frontend from 4.5.0 to 4.6.0
Bump rspec-rails from 6.0.1 to 6.0.3
Bump webpack-merge from 5.8.0 to 5.9.0
Bump sass-loader from 13.2.2 to 13.3.1
Bump sentry-rails from 5.8.0 to 5.9.0
Bump compression-webpack-plugin from 9.2.0 to 10.0.0
Bump mini-css-extract-plugin from 2.7.5 to 2.7.6
Closes #1331, #1330, #1329, #1328, #1327, #1326, #1325, #1324, #1323, #1322
=> Bump up various dependency library versions

app/views/layouts/application.html.erb
[Trello-4793](https://trello.com/c/pTz3BYQN/4793-coordinate-top-level-redirect-from-get-an-adviser-site-to-git-adviser-funnel)
Add noindex to the page template
=> Add noindex to page template

.rspec, config/routes.rb
[Trello-4793](https://trello.com/c/pTz3BYQN/4793-coordinate-top-level-redirect-from-get-an-adviser-site-to-git-adviser-funnel)
Add top level redirect FROM `https://adviser-getintoteaching.education.gov.uk/` TO `https://getintoteaching.education.gov.uk/teacher-training-adviser/sign_up/identity`
=> Add redirect from the home page to GiT

.github/workflows/actions/deploy/action.yml, .rspec, config/routes.rb, spec/requests/redirect_spec.rb
[Trello-4793](https://trello.com/c/pTz3BYQN/4793-coordinate-top-level-redirect-from-get-an-adviser-site-to-git-adviser-funnel)
Add wildcard redirect FROM `https://adviser-getintoteaching.education.gov.uk/` TO `https://getintoteaching.education.gov.uk/teacher-training-adviser/sign_up/identity` (once there are no people left in the middle of the funnel on the adviser site)
=> Add all path redirect to GiT
